namespace Application.Shared.Message
{
    public enum ChannelRecvCode
    {
        RegisterChannel,
        UnregisterChannel,
        DisconnectAll,
        InvokeDisconnectPlayer,
        SaveAll,
        InvokeSetGmLevel,
        BanPlayer,
        Unban,

        Jail,
        Unjail,

        InvokeAutoBanIgnore,
        InvokeMonitor ,
        InvokeNoteMessage ,
        SummonPlayer ,
        WarpPlayer ,
        OnPlayerJobChanged ,
        OnPlayerLevelChanged ,
        OnPlayerServerChanged ,
        DropTextMessage ,
        MultiChat ,
        HandleFullPacket ,

        OnTeamUpdate ,
        OnTeamCreated ,

        OnGuildCreated,
        OnGuildGpUpdate ,
        OnGuildRankTitleUpdate ,
        OnGuildNoticeUpdate ,
        OnGuildCapacityUpdate ,
        OnGuildEmblemUpdate ,
        OnGuildDisband ,
        OnGuildRankChanged ,
        OnGuildExpelMember ,
        OnPlayerJoinGuild ,
        OnPlayerLeaveGuild ,
        OnGuildMemberLoginOff ,
        OnGuildMemberUpdate ,

        OnAllianceCreated,
        OnGuildJoinAlliance ,
        OnGuildLeaveAlliance ,
        OnAllianceExpelGuild ,
        OnAllianceCapacityUpdate ,
        OnAllianceNoticeUpdate ,
        OnAllianceRankTitleUpdate ,
        OnAllianceMemberRankChanged ,
        OnAllianceLeaderChanged ,
        OnAllianceDisband ,
        OnAlliancePlayerInfoBroadcast ,
        OnJoinChatRoom ,
        OnLeaveChatRoom ,
        OnChatRoomMessageReceived ,
        CreateCharacter ,
        OnCouponConfigUpdate ,
        OnWorldConfigUpdate ,
        OnBuddyAdd ,
        OnBuddyRemove ,
        OnBuddyNotify ,
        OnBuddyLocation ,
        OnWhisper ,
        OnInvitationSent ,
        OnInvitationAnswered ,
        OnNewYearCardSent ,
        OnNewYearCardReceived ,
        OnNewYearCardNotify ,
        OnNewYearCardDiscard ,
        OnPlifeCreated ,
        OnPlifeRemoved ,
        HandleReportReceived ,
        HandleSetTimer ,
        HandleRemoveTimer ,
        HandleWorldEventReload ,
        HandleItemMegaphone ,
        HandleTVMessageStart ,
        HandleTVMessageFinish ,
        TakeDueyPackage ,
        TakeDueyPackageCallback ,
        CreateDueyPackage ,
        DeleteDueyPackage ,
        LoginNotifyDueyPackage ,
        LoadDueyPackage ,
        OnDoorRemoved,
    }
}
