

using provider.wz;

namespace tools.mapletools;













/**
 * @author RonanLana
 * <p>
 * This application main objective is to read Vega-related information from
 * the item's description report back missing nodes for these items.
 * <p>
 * Estimated parse time: 10 seconds
 */
public class CashVegaChecker {
    private static Path OUTPUT_FILE = ToolConstants.getOutputFile("vega_checker_report.txt");
    private static int INITIAL_STRING_LENGTH = 1000;
    private static HashSet<int> vegaItems = new ();

    private static PrintWriter printWriter = null;
    private static InputStreamReader fileReader = null;
    private static BufferedReader bufferedReader = null;
    private static int currentItem;
    private static byte status = 0;

    private static string getName(string token) {
        int i, j;
        char[] dest;
        string d;

        i = token.lastIndexOf("name");
        i = token.indexOf("\"", i) + 1; //lower bound of the string
        j = token.indexOf("\"", i);     //upper bound

        dest = new char[INITIAL_STRING_LENGTH];
        token.getChars(i, j, dest, 0);

        d = new string(dest);
        return (d.trim());
    }

    private static string getValue(string token) {
        int i, j;
        char[] dest;
        string d;

        i = token.lastIndexOf("value=");
        i = token.indexOf("\"", i) + 1; //lower bound of the string
        j = token.indexOf("\"", i);     //upper bound

        dest = new char[INITIAL_STRING_LENGTH];
        token.getChars(i, j, dest, 0);

        d = new string(dest);
        return (d.trim());
    }

    private static void forwardCursor(int st) {
        string line = null;

        try {
            while (status >= st && (line = bufferedReader.readLine()) != null) {
                simpleToken(line);
            }
        } catch (Exception e) {
            Log.Logger.Error(e.ToString());
        }
    }

    private static void simpleToken(string token) {
        if (token.Contains("/imgdir")) {
            status -= 1;
        } else if (token.Contains("imgdir")) {
            status += 1;
        }
    }

    private static void translateItemToken(string token) {
        if (token.Contains("/imgdir")) {
            status -= 1;
        } else if (token.Contains("imgdir")) {
            status += 1;

            if (status == 2) {
                currentItem = int.Parse(getName(token));
            }
        } else {
            if (status == 2) {
                if (getValue(token).endsWith("Vega&apos;s Spell.")) {
                    vegaItems.Add(currentItem);
                }
            }
        }
    }

    private static void translateVegaToken(string token) {
        if (token.Contains("/imgdir")) {
            status -= 1;
        } else if (token.Contains("imgdir")) {
            status += 1;
        } else {
            if (status == 2) {
                if (getName(token).contentEquals("item")) {
                    vegaItems.Remove(getValue(token));
                }
            }
        }
    }

    private static void readItemDescriptionFile(File f) {
        System.out.print("Reading string.wz... ");
        try {
            fileReader = new InputStreamReader(new FileInputStream(f), StandardCharsets.UTF_8);
            bufferedReader = new BufferedReader(fileReader);

            string line;
            while ((line = bufferedReader.readLine()) != null) {
                translateItemToken(line);
            }

            bufferedReader.close();
            fileReader.close();
        } catch (IOException ioe) {
            ioLog.Logger.Error(e.ToString());
        }
        Console.WriteLine(vegaItems.Count + " Vega Scroll items found");
    }

    private static void readVegaDescriptionFile(File f) {
        Console.WriteLine("Reading Etc.wz...");
        try {
            fileReader = new InputStreamReader(new FileInputStream(f), StandardCharsets.UTF_8);
            bufferedReader = new BufferedReader(fileReader);

            string line;
            while ((line = bufferedReader.readLine()) != null) {
                translateVegaToken(line);
            }

            bufferedReader.close();
            fileReader.close();
        } catch (IOException ioe) {
            ioLog.Logger.Error(e.ToString());
        }
    }

    private static void printReportFileHeader() {
        printWriter.println(" # Report File autogenerated from the MapleCashVegaChecker feature by Ronan Lana.");
        printWriter.println(" # Generated data takes into account several data info from the server-side WZ.xmls.");
        printWriter.println();
    }

    private static void reportMissingVegaItems() {
        Console.WriteLine("Reporting results ...");

        try (PrintWriter pw = new PrintWriter(Files.newOutputStream(OUTPUT_FILE))) {
            printWriter = pw;
            printReportFileHeader();

            foreach(int itemid in vegaItems) {
                printWriter.println("  " + itemid);
            }

        } catch (IOException ioe) {
            ioLog.Logger.Error(e.ToString());
        }

    }

    public static void main(string[] args) {

        readItemDescriptionFile(new File(WZFiles.STRING.getFilePath() + "/Consume.img.xml"));
        readVegaDescriptionFile(new File(WZFiles.ETC.getFilePath() + "/VegaSpell.img.xml"));

        reportMissingVegaItems();
    }

}
