

using server.life;
using tools;

namespace tools.mapletools;













/**
 * @author RonanLana
 * <p>
 * This application traces missing meso drop data on the underlying DB (that must be
 * defined on the DatabaseConnection file of this project) and generates a
 * SQL file that proposes missing drop entries for the drop_data table.
 * <p>
 * The meso range is calculated accordingly with the target mob stats, such as level
 * and if it's a boss or not, similarly as how it has been done for the actual meso
 * drops.
 */
public class SkillbookChanceFetcher {
    private static Path OUTPUT_FILE = ToolConstants.getOutputFile("skillbook_drop_data.sql");
    private static Dictionary<Pair<int, int>, int> skillbookChances = new ();

    private static PrintWriter printWriter;
    private static Dictionary<int, MonsterStats> mobStats;

    private static List<Map.Entry<Pair<int, int>, int>> sortedSkillbookChances() {
        List<Map.Entry<Pair<int, int>, int>> skillbookChancesList = new (skillbookChances);

        skillbookChancesList.sort((o1, o2) -> {
            if (o1.Key.getLeft().Equals(o2.Key.getLeft())) {
                return o1.Key.getRight() < o2.Key.getRight() ? -1 : (o1.Key.getRight().Equals(o2.Key.getRight()) ? 0 : 1);
            }

            return (o1.Key.getLeft() < o2.Key.getLeft()) ? -1 : 1;
        });

        return skillbookChancesList;
    }

    private static bool isLegendSkillUpgradeBook(int itemid) {
        int itemidBranch = itemid / 10000;
        return (itemidBranch == 228 && itemid >= 2280013 || itemidBranch == 229 && itemid >= 2290126);      // drop rate of Legends are higher
    }

    private static void fetchSkillbookDropChances() {
        Connection con = SimpleDatabaseConnection.getConnection();

        try {
            PreparedStatement ps = con.prepareStatement("SELECT dropperid, itemid FROM drop_data WHERE itemid >= 2280000 AND itemid < 2300000");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int mobid = rs.getInt("dropperid");
                int itemid = rs.getInt("itemid");

                int expectedChance = 250;

                if (mobStats.get(mobid) != null) {
                    int level = mobStats.get(mobid).getLevel();
                    expectedChance *= Math.Max(2, (level - 80) / 15);

                    if (mobStats.get(mobid).isBoss()) {
                        expectedChance *= 20;
                    } else {
                        expectedChance *= 1;
                    }
                } else {
                    expectedChance = 1287;
                }

                if (isLegendSkillUpgradeBook(itemid)) {     // drop rate of Legends seems to be higher than explorers, in retrospect from values in DB
                    expectedChance *= 3;
                }

                skillbookChances.Add(new (mobid, itemid), expectedChance);
            }

            rs.close();
            ps.close();
            con.close();
        } catch (Exception e) {
            Log.Logger.Error(e.ToString());
        }
    }

    private static void printSkillbookChanceUpdateSqlHeader() {
        printWriter.println(" # SQL File autogenerated from the MapleSkillbookChanceFetcher feature by Ronan Lana.");
        printWriter.println(" # Generated data takes into account mob stats such as level and boss for the chance rates.");
        printWriter.println();

        printWriter.println("  REPLACE INTO drop_data (`dropperid`, `itemid`, `minimum_quantity`, `maximum_quantity`, `questid`, `chance`) VALUES");
    }

    private static void generateSkillbookChanceUpdateFile() {
        try (PrintWriter pw = new PrintWriter(Files.newOutputStream(OUTPUT_FILE))) {
            printWriter = pw;

            printSkillbookChanceUpdateSqlHeader();

            List<Map.Entry<Pair<int, int>, int>> skillbookChancesList = sortedSkillbookChances();
            foreach(Map.Entry<Pair<int, int>, int> e in skillbookChancesList) {
                printWriter.println("(" + e.Key.getLeft() + ", " + e.Key.getRight() + ", 1, 1, 0, "
                        + e.getValue() + "),");
            }

        } catch (IOException ioe) {
            ioLog.Logger.Error(e.ToString());
        }
    }

    public static void main(string[] args) {
        // load mob stats from WZ
        mobStats = MonsterStatFetcher.getAllMonsterStats();

        fetchSkillbookDropChances();
        generateSkillbookChanceUpdateFile();
    }
}
