services:
  rua-ms:
    container_name: service-rua-ms-server
    image: rua-ms
    # privileged: true  # 启用特权模式
    build:
      context: .
      dockerfile: src/Application.Host/Dockerfile
    depends_on:
      rua-ms-db:
        condition: service_healthy
    environment:
        RUA_MS_DB_CONNECTIONSTRING: "server=rua-ms-db;user id=root;password=root;SslMode=None;allowPublicKeyRetrieval=true;database=ruams;Charset=utf8mb4;"
        ## 此处修改HOST
        # RUA_MS_HOST: 127.0.0.1
        # RUA_MS_LANHOST: 127.0.0.1
        # RUA_MS_LOCALHOST: 127.0.0.1
        # RUA_MS_ENABLE_OPENAPI: false
    ports:
      - "8080:8080"
      # 登录服务器
      - "8484:8484"
      # 频道服务器
      - "7575-7600:7575-7600"
    volumes:
      - ./logs:/app/logs

  rua-ms-db:
    container_name: service-rua-ms-db
    image: mysql:8.4.4
    environment:
      MYSQL_DATABASE: "ruams"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/log:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 20
      timeout: 10s