syntax = "proto3";


import "Dto/Character.proto";
import "Account/AccountInfo.proto";
import "Account/AccountGame.proto";
import "Dto/Item.proto";
import "Dto/Monsterbook.proto";
import "Dto/PetIgnore.proto";
import "Dto/TrockLocation.proto";
import "Dto/Area.proto";
import "Dto/Event.proto";
import "Dto/QuestStatus.proto";
import "Dto/Skill.proto";
import "Dto/SkillMacro.proto";
import "Dto/CoolDown.proto";
import "Dto/KeyMap.proto";
import "Dto/SavedLocation.proto";
import "Buddy/Buddy.proto";
import "Dto/NewYearCard.proto";
import "Dto/ServerCrossCallback.proto";
import "Dto/Fame.proto";
import "Sync/PlayerTimerQuest.proto";
import "Item/Ring.proto";

package SyncProto;

message LoginInfo {
	bool isNewCommer = 1;
	int32 language = 2;
}

message CharacterLinkDto {
  int32 level = 1;
  string name = 2;
}

message PlayerGetterDto {
  AccountDto.AccountInfoProto account = 1;
  Dto.CharacterDto character = 2; // CHECK TYPE
  AccountDto.AccountGameDto accountGame = 3; // 账号共享数据
  repeated ItemProto.RingDto ringSourceList = 4;
  repeated Dto.NewYearCardDto newYearCards = 5;	// 新年贺卡
  LoginInfo loginInfo = 17;
  CharacterLinkDto link = 18;
  repeated Dto.RemoteCallDto remoteCallList = 23;
}

message GetPlayerByLoginRequest {
	string clientSession = 1;
	int32 characterId = 2; 
}

message GetPlayerByLoginResponse {
	PlayerGetterDto data = 1;
}