//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Messages.ClientMessage", typeof(ClientMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 设置属性点 的本地化字符串。
        /// </summary>
        public static string ApCommand_Description {
            get {
                return ResourceManager.GetString("ApCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!ap [&lt;玩家名&gt;] &lt;属性点&gt; 的本地化字符串。
        /// </summary>
        public static string ApCommand_Syntax {
            get {
                return ResourceManager.GetString("ApCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封禁玩家。 的本地化字符串。
        /// </summary>
        public static string BanCommand_Description {
            get {
                return ResourceManager.GetString("BanCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式: !ban &lt;玩家昵称&gt; &lt;天&gt; 的本地化字符串。
        /// </summary>
        public static string BanCommand_Syntax {
            get {
                return ResourceManager.GetString("BanCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封禁原因： 的本地化字符串。
        /// </summary>
        public static string BanReason {
            get {
                return ResourceManager.GetString("BanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置boss掉率。 的本地化字符串。
        /// </summary>
        public static string BossDropRateCommand_Description {
            get {
                return ResourceManager.GetString("BossDropRateCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前地图的boss血量。 的本地化字符串。
        /// </summary>
        public static string BossHpCommand_Description {
            get {
                return ResourceManager.GetString("BossHpCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ({1}) 剩余 {2}% 血量 的本地化字符串。
        /// </summary>
        public static string BossHpCommand_Message1 {
            get {
                return ResourceManager.GetString("BossHpCommand_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 血量：{0} 的本地化字符串。
        /// </summary>
        public static string BossHpCommand_Message2 {
            get {
                return ResourceManager.GetString("BossHpCommand_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给玩家附加buff。 的本地化字符串。
        /// </summary>
        public static string BuffCommand_Description {
            get {
                return ResourceManager.GetString("BuffCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!buff &lt;buffid&gt; 的本地化字符串。
        /// </summary>
        public static string BuffCommand_Syntax {
            get {
                return ResourceManager.GetString("BuffCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附加一些增益buff 的本地化字符串。
        /// </summary>
        public static string BuffMeCommand_Description {
            get {
                return ResourceManager.GetString("BuffMeCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能传送到自己。 的本地化字符串。
        /// </summary>
        public static string CannotWarpMySelf {
            get {
                return ResourceManager.GetString("CannotWarpMySelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法执行该操作，玩家人气值已经达到了上限/下限。 的本地化字符串。
        /// </summary>
        public static string ChangeFame_OutOfRange {
            get {
                return ResourceManager.GetString("ChangeFame_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道 的本地化字符串。
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换GM的聊天类型 的本地化字符串。
        /// </summary>
        public static string ChatCommand_Description {
            get {
                return ResourceManager.GetString("ChatCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示玩家状态和伤害。 的本地化字符串。
        /// </summary>
        public static string CheckDmgCommand_Description {
            get {
                return ResourceManager.GetString("CheckDmgCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 力量：{0}，敏捷：{1}，智力：{2}，运气：{3} 的本地化字符串。
        /// </summary>
        public static string CheckDmgCommand_Message1 {
            get {
                return ResourceManager.GetString("CheckDmgCommand_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物理攻击：{0}，魔法攻击：{1} 的本地化字符串。
        /// </summary>
        public static string CheckDmgCommand_Message2 {
            get {
                return ResourceManager.GetString("CheckDmgCommand_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物理攻击buff：{0}，魔法攻击buff：{1}，祝福等级：{2} 的本地化字符串。
        /// </summary>
        public static string CheckDmgCommand_Message3 {
            get {
                return ResourceManager.GetString("CheckDmgCommand_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的最大基础伤害：{1} 的本地化字符串。
        /// </summary>
        public static string CheckDmgCommand_Message4 {
            get {
                return ResourceManager.GetString("CheckDmgCommand_Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理一些缓存。 的本地化字符串。
        /// </summary>
        public static string ClearCacheCommand_Description {
            get {
                return ResourceManager.GetString("ClearCacheCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有窗口都已清理 的本地化字符串。
        /// </summary>
        public static string ClearSlotCommand_AllCleared {
            get {
                return ResourceManager.GetString("ClearSlotCommand_AllCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现金栏已清理 的本地化字符串。
        /// </summary>
        public static string ClearSlotCommand_CashCleared {
            get {
                return ResourceManager.GetString("ClearSlotCommand_CashCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消耗栏已清理 的本地化字符串。
        /// </summary>
        public static string ClearSlotCommand_ConsumeCleared {
            get {
                return ResourceManager.GetString("ClearSlotCommand_ConsumeCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理背包 的本地化字符串。
        /// </summary>
        public static string ClearSlotCommand_Description {
            get {
                return ResourceManager.GetString("ClearSlotCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装备栏已清理 的本地化字符串。
        /// </summary>
        public static string ClearSlotCommand_EquipCleared {
            get {
                return ResourceManager.GetString("ClearSlotCommand_EquipCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他栏已清理 的本地化字符串。
        /// </summary>
        public static string ClearSlotCommand_EtcCleared {
            get {
                return ResourceManager.GetString("ClearSlotCommand_EtcCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置栏已清理 的本地化字符串。
        /// </summary>
        public static string ClearSlotCommand_InstallCleared {
            get {
                return ResourceManager.GetString("ClearSlotCommand_InstallCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!clearslot &lt;all, equip, use, setup, etc or cash.&gt; 的本地化字符串。
        /// </summary>
        public static string ClearSlotCommand_Syntax {
            get {
                return ResourceManager.GetString("ClearSlotCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令 {0} 已完成。 的本地化字符串。
        /// </summary>
        public static string Command_Done {
            get {
                return ResourceManager.GetString("Command_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送到 {0} 身边？ 的本地化字符串。
        /// </summary>
        public static string ConfirmWarpTo {
            get {
                return ResourceManager.GetString("ConfirmWarpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前地图：{0} 的本地化字符串。
        /// </summary>
        public static string CurrentMap {
            get {
                return ResourceManager.GetString("CurrentMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字 的本地化字符串。
        /// </summary>
        public static string DataType_Number {
            get {
                return ResourceManager.GetString("DataType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型不正确，期望类型：{0} 的本地化字符串。
        /// </summary>
        public static string DataTypeIncorrect {
            get {
                return ResourceManager.GetString("DataTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开所有在线玩家连接 的本地化字符串。
        /// </summary>
        public static string DCAllCommand_Description {
            get {
                return ResourceManager.GetString("DCAllCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使玩家下线。 的本地化字符串。
        /// </summary>
        public static string DcCommand_Description {
            get {
                return ResourceManager.GetString("DcCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给附近玩家上debuff 的本地化字符串。
        /// </summary>
        public static string DebuffCommand_Description {
            get {
                return ResourceManager.GetString("DebuffCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!debuff SLOW|SEDUCE|ZOMBIFY|CONFUSE|STUN|POISON|SEAL|DARKNESS|WEAKEN|CURSE 的本地化字符串。
        /// </summary>
        public static string DebuffCommand_Syntax {
            get {
                return ResourceManager.GetString("DebuffCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解卡 的本地化字符串。
        /// </summary>
        public static string DisposeCommand_Description {
            get {
                return ResourceManager.GetString("DisposeCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解卡成功。 的本地化字符串。
        /// </summary>
        public static string DisposeCommand_Message1 {
            get {
                return ResourceManager.GetString("DisposeCommand_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前GM等级不能丢出物品 的本地化字符串。
        /// </summary>
        public static string DropItem_NoAccess {
            get {
                return ResourceManager.GetString("DropItem_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前地图最大掉落数 的本地化字符串。
        /// </summary>
        public static string DropLimitCommand_Description {
            get {
                return ResourceManager.GetString("DropLimitCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已掉落数量： 的本地化字符串。
        /// </summary>
        public static string DropLimitCommand_Message1 {
            get {
                return ResourceManager.GetString("DropLimitCommand_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前GM等级不能丢出金币 的本地化字符串。
        /// </summary>
        public static string DropMeso_NotAccess {
            get {
                return ResourceManager.GetString("DropMeso_NotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置掉落倍率。 的本地化字符串。
        /// </summary>
        public static string DropRateCommand_Description {
            get {
                return ResourceManager.GetString("DropRateCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示已穿戴装备等级信息。 的本地化字符串。
        /// </summary>
        public static string EquipLvCommand_Description {
            get {
                return ResourceManager.GetString("EquipLvCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不存在 或者并不是一件装备。 的本地化字符串。
        /// </summary>
        public static string EquipNotFound {
            get {
                return ResourceManager.GetString("EquipNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置经验倍率。 的本地化字符串。
        /// </summary>
        public static string ExpRateCommand_Description {
            get {
                return ResourceManager.GetString("ExpRateCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改变玩家的脸型 的本地化字符串。
        /// </summary>
        public static string FaceCommand_Description {
            get {
                return ResourceManager.GetString("FaceCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!face &lt;玩家名&gt; &lt;脸型id&gt; 的本地化字符串。
        /// </summary>
        public static string FaceCommand_Syntax {
            get {
                return ResourceManager.GetString("FaceCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到Id=“{0}”的脸型 的本地化字符串。
        /// </summary>
        public static string FaceNotFound {
            get {
                return ResourceManager.GetString("FaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改玩家人气值 的本地化字符串。
        /// </summary>
        public static string FameCommand_Description {
            get {
                return ResourceManager.GetString("FameCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人气 已发放。 的本地化字符串。
        /// </summary>
        public static string FameCommand_FameGiven {
            get {
                return ResourceManager.GetString("FameCommand_FameGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!fame [&lt;玩家名&gt;] &lt;设置值&gt; 的本地化字符串。
        /// </summary>
        public static string FameCommand_Syntax {
            get {
                return ResourceManager.GetString("FameCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能未启用。 的本地化字符串。
        /// </summary>
        public static string FeatureUnavailable {
            get {
                return ResourceManager.GetString("FeatureUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找到相似项： 的本地化字符串。
        /// </summary>
        public static string FindSimilarItem {
            get {
                return ResourceManager.GetString("FindSimilarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置钓鱼倍率。 的本地化字符串。
        /// </summary>
        public static string FishingRateCommand_Description {
            get {
                return ResourceManager.GetString("FishingRateCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示扭蛋奖励。 的本地化字符串。
        /// </summary>
        public static string GachaCommand_Description {
            get {
                return ResourceManager.GetString("GachaCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #b{0}#k拥有以下奖励。\r\n\r\n 的本地化字符串。
        /// </summary>
        public static string GachaCommand_Message1 {
            get {
                return ResourceManager.GetString("GachaCommand_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请注意，所有扭蛋机都有的奖励不会在这里显示。 的本地化字符串。
        /// </summary>
        public static string GachaCommand_Message2 {
            get {
                return ResourceManager.GetString("GachaCommand_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用 !gacha &lt;城镇名&gt; 查询奖励列表： 的本地化字符串。
        /// </summary>
        public static string GachaCommand_Syntax {
            get {
                return ResourceManager.GetString("GachaCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给玩家金币。 的本地化字符串。
        /// </summary>
        public static string GiveMesosCommand_Description {
            get {
                return ResourceManager.GetString("GiveMesosCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金币 已发放。 的本地化字符串。
        /// </summary>
        public static string GiveMesosCommand_MesoGiven {
            get {
                return ResourceManager.GetString("GiveMesosCommand_MesoGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!givems &lt;玩家名&gt; &lt;金币&gt; 的本地化字符串。
        /// </summary>
        public static string GiveMesosCommand_Syntax {
            get {
                return ResourceManager.GetString("GiveMesosCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给玩家点券。 的本地化字符串。
        /// </summary>
        public static string GiveNxCommand_Description {
            get {
                return ResourceManager.GetString("GiveNxCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!givenx [nx, mp, np] [&lt;玩家名&gt;] &lt;点券&gt; 的本地化字符串。
        /// </summary>
        public static string GiveNxCommand_Syntax {
            get {
                return ResourceManager.GetString("GiveNxCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改变玩家的发型 的本地化字符串。
        /// </summary>
        public static string HairCommand_Description {
            get {
                return ResourceManager.GetString("HairCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!hair [&lt;玩家名&gt;] &lt;发型id&gt; 的本地化字符串。
        /// </summary>
        public static string HairCommand_Syntax {
            get {
                return ResourceManager.GetString("HairCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到Id=“{0}”的发型 的本地化字符串。
        /// </summary>
        public static string HairNotFound {
            get {
                return ResourceManager.GetString("HairNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前等级可用命令。 的本地化字符串。
        /// </summary>
        public static string HelpCommand_Description {
            get {
                return ResourceManager.GetString("HelpCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持通过命令创建现金道具 的本地化字符串。
        /// </summary>
        public static string ItemCommand_CannotCreateCashItem {
            get {
                return ResourceManager.GetString("ItemCommand_CannotCreateCashItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成物品到背包 的本地化字符串。
        /// </summary>
        public static string ItemCommand_Description {
            get {
                return ResourceManager.GetString("ItemCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!item &lt;宠物Id&gt; &lt;有效期&gt; 的本地化字符串。
        /// </summary>
        public static string ItemCommand_PetSyntax {
            get {
                return ResourceManager.GetString("ItemCommand_PetSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!item &lt;物品Id&gt; &lt;数量&gt; 的本地化字符串。
        /// </summary>
        public static string ItemCommand_Syntax {
            get {
                return ResourceManager.GetString("ItemCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持通过命令创建现金道具 的本地化字符串。
        /// </summary>
        public static string ItemDropCommand_CannotCreateCashItem {
            get {
                return ResourceManager.GetString("ItemDropCommand_CannotCreateCashItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成掉落物 的本地化字符串。
        /// </summary>
        public static string ItemDropCommand_Description {
            get {
                return ResourceManager.GetString("ItemDropCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!drop &lt;宠物Id&gt; &lt;有效期&gt; 的本地化字符串。
        /// </summary>
        public static string ItemDropCommand_PetSyntax {
            get {
                return ResourceManager.GetString("ItemDropCommand_PetSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!drop &lt;物品id/物品名称&gt; &lt;数量&gt; 的本地化字符串。
        /// </summary>
        public static string ItemDropCommand_Syntax {
            get {
                return ResourceManager.GetString("ItemDropCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品Id={0} 不存在。 的本地化字符串。
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接发放任务所需的道具，生成任务需要击杀的怪物。 的本地化字符串。
        /// </summary>
        public static string ItemQuestCommand_Description {
            get {
                return ResourceManager.GetString("ItemQuestCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 {0} 在小黑屋的时间延长{1}分钟。 的本地化字符串。
        /// </summary>
        public static string Jail_ExtendResult {
            get {
                return ResourceManager.GetString("Jail_ExtendResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 {0} 已被拉进小黑屋（{1}分钟）。 的本地化字符串。
        /// </summary>
        public static string Jail_Result {
            get {
                return ResourceManager.GetString("Jail_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小黑屋。 的本地化字符串。
        /// </summary>
        public static string JailCommand_Description {
            get {
                return ResourceManager.GetString("JailCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!jail &lt;玩家名&gt; [&lt;分钟，默认5&gt;] 的本地化字符串。
        /// </summary>
        public static string JailCommand_Syntax {
            get {
                return ResourceManager.GetString("JailCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改职业。 的本地化字符串。
        /// </summary>
        public static string JobCommand_Description {
            get {
                return ResourceManager.GetString("JobCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!job &lt;job id&gt; [&lt;playername&gt;] 的本地化字符串。
        /// </summary>
        public static string JobCommand_Syntax {
            get {
                return ResourceManager.GetString("JobCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到 {0} 的职业 的本地化字符串。
        /// </summary>
        public static string JobNotFound {
            get {
                return ResourceManager.GetString("JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击杀地图上的所有怪物。 的本地化字符串。
        /// </summary>
        public static string KillAllCommand_Description {
            get {
                return ResourceManager.GetString("KillAllCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击杀了{0}个怪物。 的本地化字符串。
        /// </summary>
        public static string KillAllCommand_MonsterKilled {
            get {
                return ResourceManager.GetString("KillAllCommand_MonsterKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击杀玩家。 的本地化字符串。
        /// </summary>
        public static string KillCommand_Description {
            get {
                return ResourceManager.GetString("KillCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!kill &lt;玩家名&gt; 的本地化字符串。
        /// </summary>
        public static string KillCommand_Syntax {
            get {
                return ResourceManager.GetString("KillCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击杀地图上的所有玩家。 的本地化字符串。
        /// </summary>
        public static string KillMapCommand_Description {
            get {
                return ResourceManager.GetString("KillMapCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置等级 的本地化字符串。
        /// </summary>
        public static string LevelCommand_Description {
            get {
                return ResourceManager.GetString("LevelCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语法：!level &lt;newlevel&gt; 的本地化字符串。
        /// </summary>
        public static string LevelCommand_Syntax {
            get {
                return ResourceManager.GetString("LevelCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 魔法森林 的本地化字符串。
        /// </summary>
        public static string Map_Ellinia {
            get {
                return ResourceManager.GetString("Map_Ellinia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 射手村 的本地化字符串。
        /// </summary>
        public static string Map_Henesys {
            get {
                return ResourceManager.GetString("Map_Henesys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 废弃都市 的本地化字符串。
        /// </summary>
        public static string Map_KerningCity {
            get {
                return ResourceManager.GetString("Map_KerningCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 古代神社 的本地化字符串。
        /// </summary>
        public static string Map_MushroomShrine {
            get {
                return ResourceManager.GetString("Map_MushroomShrine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诺特勒斯 的本地化字符串。
        /// </summary>
        public static string Map_NautilusHarbor {
            get {
                return ResourceManager.GetString("Map_NautilusHarbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新叶城 的本地化字符串。
        /// </summary>
        public static string Map_NewLeafCity {
            get {
                return ResourceManager.GetString("Map_NewLeafCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勇士部落 的本地化字符串。
        /// </summary>
        public static string Map_Perion {
            get {
                return ResourceManager.GetString("Map_Perion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昭和村更衣室(女) 的本地化字符串。
        /// </summary>
        public static string Map_ShowaSpaFemale {
            get {
                return ResourceManager.GetString("Map_ShowaSpaFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昭和村更衣室(男) 的本地化字符串。
        /// </summary>
        public static string Map_ShowaSpaMale {
            get {
                return ResourceManager.GetString("Map_ShowaSpaMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 林中之城 的本地化字符串。
        /// </summary>
        public static string Map_Sleepywood {
            get {
                return ResourceManager.GetString("Map_Sleepywood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图 {0} 不存在 的本地化字符串。
        /// </summary>
        public static string MapNotFound {
            get {
                return ResourceManager.GetString("MapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明地图归属。 的本地化字符串。
        /// </summary>
        public static string MapOwnerClaimCommand_Description {
            get {
                return ResourceManager.GetString("MapOwnerClaimCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图归属已释放。 的本地化字符串。
        /// </summary>
        public static string MapOwnerClaimCommand_Message1 {
            get {
                return ResourceManager.GetString("MapOwnerClaimCommand_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已获得地图归属权，直到离开地图或挂机超过1分钟。 的本地化字符串。
        /// </summary>
        public static string MapOwnerClaimCommand_Message2 {
            get {
                return ResourceManager.GetString("MapOwnerClaimCommand_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该地图已存在归属。 的本地化字符串。
        /// </summary>
        public static string MapOwnerClaimCommand_Message3 {
            get {
                return ResourceManager.GetString("MapOwnerClaimCommand_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BOSS地图无法归属玩家 的本地化字符串。
        /// </summary>
        public static string MapOwnerClaimCommand_Message4 {
            get {
                return ResourceManager.GetString("MapOwnerClaimCommand_Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取该地图归属 的本地化字符串。
        /// </summary>
        public static string MapOwnerClaimCommand_Message5 {
            get {
                return ResourceManager.GetString("MapOwnerClaimCommand_Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前地图上的所有玩家。 的本地化字符串。
        /// </summary>
        public static string MapPlayersCommand_Description {
            get {
                return ResourceManager.GetString("MapPlayersCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 技能全满。 的本地化字符串。
        /// </summary>
        public static string MaxSkillCommand_Description {
            get {
                return ResourceManager.GetString("MaxSkillCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 技能已全满。 的本地化字符串。
        /// </summary>
        public static string MaxSkillCommand_Result {
            get {
                return ResourceManager.GetString("MaxSkillCommand_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性全满。 的本地化字符串。
        /// </summary>
        public static string MaxStatCommand_Description {
            get {
                return ResourceManager.GetString("MaxStatCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性已全满。 的本地化字符串。
        /// </summary>
        public static string MaxStatCommand_Result {
            get {
                return ResourceManager.GetString("MaxStatCommand_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置金币倍率。 的本地化字符串。
        /// </summary>
        public static string MesoRateCommand_Description {
            get {
                return ResourceManager.GetString("MesoRateCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示地图上所有怪物HP。 的本地化字符串。
        /// </summary>
        public static string MobHpCommand_Description {
            get {
                return ResourceManager.GetString("MobHpCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物Id={0} 不存在 的本地化字符串。
        /// </summary>
        public static string MobNotFound {
            get {
                return ResourceManager.GetString("MobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置全局怪物倍率，范围：(0, 5] 的本地化字符串。
        /// </summary>
        public static string MobRateCommand_Description {
            get {
                return ResourceManager.GetString("MobRateCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对地图上所有怪物施加怪物技能。 的本地化字符串。
        /// </summary>
        public static string MobSkillCommand_Description {
            get {
                return ResourceManager.GetString("MobSkillCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!mobskill &lt;技能id&gt; &lt;技能等级&gt; 的本地化字符串。
        /// </summary>
        public static string MobSkillCommand_Syntax {
            get {
                return ResourceManager.GetString("MobSkillCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物技能Id={0}不存在。 的本地化字符串。
        /// </summary>
        public static string MobSkillNotFound {
            get {
                return ResourceManager.GetString("MobSkillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有在线玩家。 的本地化字符串。
        /// </summary>
        public static string OnlineCommand_Description {
            get {
                return ResourceManager.GetString("OnlineCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有在当前频道找到玩家“{0}” 的本地化字符串。
        /// </summary>
        public static string PlayerNotFoundInChannel {
            get {
                return ResourceManager.GetString("PlayerNotFoundInChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有在当前地图找到玩家“{0}” 的本地化字符串。
        /// </summary>
        public static string PlayerNotFoundInMap {
            get {
                return ResourceManager.GetString("PlayerNotFoundInMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在当前位置生成一个NPC 的本地化字符串。
        /// </summary>
        public static string PnpcCommand_Description {
            get {
                return ResourceManager.GetString("PnpcCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!pnpc &lt;npcid&gt; 的本地化字符串。
        /// </summary>
        public static string PnpcCommand_Syntax {
            get {
                return ResourceManager.GetString("PnpcCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成装备 的本地化字符串。
        /// </summary>
        public static string ProItemCommand_Description {
            get {
                return ResourceManager.GetString("ProItemCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!proitem &lt;装备id&gt; &lt;stat value&gt; [&lt;spdjmp value&gt;] 的本地化字符串。
        /// </summary>
        public static string ProItemCommand_Syntax {
            get {
                return ResourceManager.GetString("ProItemCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成任务。 的本地化字符串。
        /// </summary>
        public static string QuestCompleteCommand_Description {
            get {
                return ResourceManager.GetString("QuestCompleteCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务 {0} 未找到。 的本地化字符串。
        /// </summary>
        public static string QuestNotFound {
            get {
                return ResourceManager.GetString("QuestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置任务奖励倍率 的本地化字符串。
        /// </summary>
        public static string QuestRateCommand_Description {
            get {
                return ResourceManager.GetString("QuestRateCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示玩家排名。 的本地化字符串。
        /// </summary>
        public static string RanksCommand_Description {
            get {
                return ResourceManager.GetString("RanksCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BOSS掉落倍率 的本地化字符串。
        /// </summary>
        public static string Rate_BossDrop {
            get {
                return ResourceManager.GetString("Rate_BossDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爆率卡倍率 的本地化字符串。
        /// </summary>
        public static string Rate_CouponDrop {
            get {
                return ResourceManager.GetString("Rate_CouponDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经验卡倍率 的本地化字符串。
        /// </summary>
        public static string Rate_CouponExp {
            get {
                return ResourceManager.GetString("Rate_CouponExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金币卡倍率 的本地化字符串。
        /// </summary>
        public static string Rate_CouponMeso {
            get {
                return ResourceManager.GetString("Rate_CouponMeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 掉落倍率 的本地化字符串。
        /// </summary>
        public static string Rate_Drop {
            get {
                return ResourceManager.GetString("Rate_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经验倍率 的本地化字符串。
        /// </summary>
        public static string Rate_Exp {
            get {
                return ResourceManager.GetString("Rate_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金币倍率 的本地化字符串。
        /// </summary>
        public static string Rate_Meso {
            get {
                return ResourceManager.GetString("Rate_Meso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家BOSS掉落倍率 的本地化字符串。
        /// </summary>
        public static string Rate_PlayerBossDrop {
            get {
                return ResourceManager.GetString("Rate_PlayerBossDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家掉落倍率 的本地化字符串。
        /// </summary>
        public static string Rate_PlayerDrop {
            get {
                return ResourceManager.GetString("Rate_PlayerDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家经验倍率 的本地化字符串。
        /// </summary>
        public static string Rate_PlayerExp {
            get {
                return ResourceManager.GetString("Rate_PlayerExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家金币倍率 的本地化字符串。
        /// </summary>
        public static string Rate_PlayerMeso {
            get {
                return ResourceManager.GetString("Rate_PlayerMeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家基础掉落倍率 的本地化字符串。
        /// </summary>
        public static string Rate_PlayerRawDrop {
            get {
                return ResourceManager.GetString("Rate_PlayerRawDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家基础经验倍率 的本地化字符串。
        /// </summary>
        public static string Rate_PlayerRawExp {
            get {
                return ResourceManager.GetString("Rate_PlayerRawExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家基础金币倍率 的本地化字符串。
        /// </summary>
        public static string Rate_PlayerRawMeso {
            get {
                return ResourceManager.GetString("Rate_PlayerRawMeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务奖励倍率 的本地化字符串。
        /// </summary>
        public static string Rate_Quest {
            get {
                return ResourceManager.GetString("Rate_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器BOSS掉落倍率 的本地化字符串。
        /// </summary>
        public static string Rate_WorldBossDrop {
            get {
                return ResourceManager.GetString("Rate_WorldBossDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器掉落倍率 的本地化字符串。
        /// </summary>
        public static string Rate_WorldDrop {
            get {
                return ResourceManager.GetString("Rate_WorldDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器经验倍率 的本地化字符串。
        /// </summary>
        public static string Rate_WorldExp {
            get {
                return ResourceManager.GetString("Rate_WorldExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器金币倍率 的本地化字符串。
        /// </summary>
        public static string Rate_WorldMeso {
            get {
                return ResourceManager.GetString("Rate_WorldMeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器任务奖励倍率 的本地化字符串。
        /// </summary>
        public static string Rate_WorldQuest {
            get {
                return ResourceManager.GetString("Rate_WorldQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器传送时间倍率 的本地化字符串。
        /// </summary>
        public static string Rate_WorldTravel {
            get {
                return ResourceManager.GetString("Rate_WorldTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过名称查找id 的本地化字符串。
        /// </summary>
        public static string SearchCommand_Description {
            get {
                return ResourceManager.GetString("SearchCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!search &lt;类型&gt; &lt;名称&gt; 的本地化字符串。
        /// </summary>
        public static string SearchCommand_Syntax {
            get {
                return ResourceManager.GetString("SearchCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找失败。Type只能是MAP, QUEST, NPC, ITEM, MOB, or SKILL 的本地化字符串。
        /// </summary>
        public static string SearchCommand_Wrong {
            get {
                return ResourceManager.GetString("SearchCommand_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在月妙副本中快速放种子。 的本地化字符串。
        /// </summary>
        public static string SeedCommand_Description {
            get {
                return ResourceManager.GetString("SeedCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个命令只能在月妙副本中执行。 的本地化字符串。
        /// </summary>
        public static string SeedCommand_LimitMessage {
            get {
                return ResourceManager.GetString("SeedCommand_LimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器时间： 的本地化字符串。
        /// </summary>
        public static string ServerTime {
            get {
                return ResourceManager.GetString("ServerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给玩家设置GM等级。 的本地化字符串。
        /// </summary>
        public static string SetGmLevelCommand_Description {
            get {
                return ResourceManager.GetString("SetGmLevelCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!setgmlevel &lt;玩家名&gt; &lt;等级&gt; 的本地化字符串。
        /// </summary>
        public static string SetGmLevelCommand_Syntax {
            get {
                return ResourceManager.GetString("SetGmLevelCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置所有背包格子数 的本地化字符串。
        /// </summary>
        public static string SetSlotCommand_Description {
            get {
                return ResourceManager.GetString("SetSlotCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!setslot &lt;数量&gt; 的本地化字符串。
        /// </summary>
        public static string SetSlotCommand_Syntax {
            get {
                return ResourceManager.GetString("SetSlotCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置所有属性 的本地化字符串。
        /// </summary>
        public static string SetStatCommand_Description {
            get {
                return ResourceManager.GetString("SetStatCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示各种倍率设置。 的本地化字符串。
        /// </summary>
        public static string ShowRatesCommand_Description {
            get {
                return ResourceManager.GetString("ShowRatesCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止服务器。 的本地化字符串。
        /// </summary>
        public static string ShutdownCommand_Description {
            get {
                return ResourceManager.GetString("ShutdownCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!shutdown [&lt;秒&gt;| -1] 的本地化字符串。
        /// </summary>
        public static string ShutdownCommand_Syntax {
            get {
                return ResourceManager.GetString("ShutdownCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在当前位置生成怪物。 的本地化字符串。
        /// </summary>
        public static string SpawnCommand_Description {
            get {
                return ResourceManager.GetString("SpawnCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!spawn &lt;怪物id/怪物名&gt; [&lt;数量&gt;] 的本地化字符串。
        /// </summary>
        public static string SpawnCommand_Syntax {
            get {
                return ResourceManager.GetString("SpawnCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置技能点 的本地化字符串。
        /// </summary>
        public static string SpCommand_Description {
            get {
                return ResourceManager.GetString("SpCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!sp [&lt;玩家名&gt;] &lt;技能点&gt; 的本地化字符串。
        /// </summary>
        public static string SpCommand_Syntax {
            get {
                return ResourceManager.GetString("SpCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 把玩家传送到这里。 的本地化字符串。
        /// </summary>
        public static string SummonCommand_Description {
            get {
                return ResourceManager.GetString("SummonCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!{0} &lt;玩家名&gt; 的本地化字符串。
        /// </summary>
        public static string SummonCommand_Syntax {
            get {
                return ResourceManager.GetString("SummonCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示服务器时间。 的本地化字符串。
        /// </summary>
        public static string TimeCommand_Description {
            get {
                return ResourceManager.GetString("TimeCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对所有玩家显示计时器。 的本地化字符串。
        /// </summary>
        public static string TimerAllCommand_Description {
            get {
                return ResourceManager.GetString("TimerAllCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!timerall &lt;秒&gt;|remove 的本地化字符串。
        /// </summary>
        public static string TimerAllCommand_Syntax {
            get {
                return ResourceManager.GetString("TimerAllCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对当前地图的某个玩家显示计时器。 的本地化字符串。
        /// </summary>
        public static string TimerCommand_Description {
            get {
                return ResourceManager.GetString("TimerCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!timer &lt;玩家名&gt; &lt;秒&gt;|remove 的本地化字符串。
        /// </summary>
        public static string TimerCommand_Syntax {
            get {
                return ResourceManager.GetString("TimerCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对地图内所有玩家显示计时器。 的本地化字符串。
        /// </summary>
        public static string TimerMapCommand_Description {
            get {
                return ResourceManager.GetString("TimerMapCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式： !timermap &lt;seconds&gt;|remove 的本地化字符串。
        /// </summary>
        public static string TimerMapCommand_Syntax {
            get {
                return ResourceManager.GetString("TimerMapCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启/关闭经验获取 的本地化字符串。
        /// </summary>
        public static string ToggleExpCommand_Description {
            get {
                return ResourceManager.GetString("ToggleExpCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另一名玩家已经完成了交易。 的本地化字符串。
        /// </summary>
        public static string Trade_AlreadyClosed {
            get {
                return ResourceManager.GetString("Trade_AlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经处理了该玩家的交易邀请。 的本地化字符串。
        /// </summary>
        public static string Trade_AlreadyManaged {
            get {
                return ResourceManager.GetString("Trade_AlreadyManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经处理了其他玩家的交易邀请。 的本地化字符串。
        /// </summary>
        public static string Trade_AlreadyManaged2 {
            get {
                return ResourceManager.GetString("Trade_AlreadyManaged2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GM不能与非GM玩家交易 的本地化字符串。
        /// </summary>
        public static string Trade_GMCheck {
            get {
                return ResourceManager.GetString("Trade_GMCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你不能与GM玩家交易 的本地化字符串。
        /// </summary>
        public static string Trade_GMCheck2 {
            get {
                return ResourceManager.GetString("Trade_GMCheck2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易中 的本地化字符串。
        /// </summary>
        public static string Trade_Ing {
            get {
                return ResourceManager.GetString("Trade_Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的背包空间不足，交易失败。 的本地化字符串。
        /// </summary>
        public static string Trade_InventoryExceedLimit {
            get {
                return ResourceManager.GetString("Trade_InventoryExceedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对方背包空间不足，交易失败。 的本地化字符串。
        /// </summary>
        public static string Trade_InventoryExceedLimit2 {
            get {
                return ResourceManager.GetString("Trade_InventoryExceedLimit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易邀请已取消 的本地化字符串。
        /// </summary>
        public static string Trade_InviteCanceld {
            get {
                return ResourceManager.GetString("Trade_InviteCanceld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已超过携带金币上限，交易失败。 的本地化字符串。
        /// </summary>
        public static string Trade_MesoExceedLimit {
            get {
                return ResourceManager.GetString("Trade_MesoExceedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对方携带金币已超过上限，交易失败。 的本地化字符串。
        /// </summary>
        public static string Trade_MesoExceedLimit2 {
            get {
                return ResourceManager.GetString("Trade_MesoExceedLimit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另一名玩家正在处理交易邀请。 的本地化字符串。
        /// </summary>
        public static string Trade_TargetInTradeManaging {
            get {
                return ResourceManager.GetString("Trade_TargetInTradeManaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另一名玩家正在交易 的本地化字符串。
        /// </summary>
        public static string Trade_TargetInTrading {
            get {
                return ResourceManager.GetString("Trade_TargetInTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对方无法同时持有多个唯一物品，交易失败。 的本地化字符串。
        /// </summary>
        public static string Trade_UniqueLimit {
            get {
                return ResourceManager.GetString("Trade_UniqueLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置各类传送时间速率。 的本地化字符串。
        /// </summary>
        public static string TravelRateCommand_Description {
            get {
                return ResourceManager.GetString("TravelRateCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于缺乏具体的证据，您已被释放，享受自由吧！ 的本地化字符串。
        /// </summary>
        public static string Unjail_Notify {
            get {
                return ResourceManager.GetString("Unjail_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个玩家不在小黑屋。 的本地化字符串。
        /// </summary>
        public static string UnjailCommand_AlreadyFree {
            get {
                return ResourceManager.GetString("UnjailCommand_AlreadyFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放出小黑屋的玩家。 的本地化字符串。
        /// </summary>
        public static string UnJailCommand_Description {
            get {
                return ResourceManager.GetString("UnJailCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!unjail &lt;玩家名&gt; 的本地化字符串。
        /// </summary>
        public static string UnJailCommand_Syntax {
            get {
                return ResourceManager.GetString("UnJailCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前服务器已运行时长。 的本地化字符串。
        /// </summary>
        public static string UptimeCommand_Description {
            get {
                return ResourceManager.GetString("UptimeCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器已运行{0}。 的本地化字符串。
        /// </summary>
        public static string UptimeCommand_Message1 {
            get {
                return ResourceManager.GetString("UptimeCommand_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带着周围的玩家一起传送。 的本地化字符串。
        /// </summary>
        public static string WarpAreaCommand_Description {
            get {
                return ResourceManager.GetString("WarpAreaCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!warparea &lt;地图id&gt; 的本地化字符串。
        /// </summary>
        public static string WarpAreaCommand_Syntax {
            get {
                return ResourceManager.GetString("WarpAreaCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送到地图 的本地化字符串。
        /// </summary>
        public static string WarpCommand_Description {
            get {
                return ResourceManager.GetString("WarpCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语法错误：!warp &lt;地图Id/地图名&gt; 的本地化字符串。
        /// </summary>
        public static string WarpCommand_Syntax {
            get {
                return ResourceManager.GetString("WarpCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 把当前地图的所有玩家传送到新的地图。 的本地化字符串。
        /// </summary>
        public static string WarpMapCommand_Description {
            get {
                return ResourceManager.GetString("WarpMapCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!warpmap &lt;地图Id/地图名&gt; 的本地化字符串。
        /// </summary>
        public static string WarpMapCommand_Syntax {
            get {
                return ResourceManager.GetString("WarpMapCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示怪物的掉落物。 的本地化字符串。
        /// </summary>
        public static string WhatDropsFromCommand_Description {
            get {
                return ResourceManager.GetString("WhatDropsFromCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!whatdropsfrom &lt;怪物名&gt; 的本地化字符串。
        /// </summary>
        public static string WhatDropsFromCommand_Syntax {
            get {
                return ResourceManager.GetString("WhatDropsFromCommand_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前所在地图信息。 的本地化字符串。
        /// </summary>
        public static string WhereaMiCommand_Description {
            get {
                return ResourceManager.GetString("WhereaMiCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示哪些怪物掉落指定物品。 的本地化字符串。
        /// </summary>
        public static string WhoDropsCommand_Description {
            get {
                return ResourceManager.GetString("WhoDropsCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式：!whodrops &lt;物品名&gt; 的本地化字符串。
        /// </summary>
        public static string WhoDropsCommand_Syntax {
            get {
                return ResourceManager.GetString("WhoDropsCommand_Syntax", resourceCulture);
            }
        }
    }
}
