//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScriptTalk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptTalk() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Messages.ScriptTalk", typeof(ScriptTalk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要离开吗？ 的本地化字符串。
        /// </summary>
        public static string AreYouReturning {
            get {
                return ResourceManager.GetString("AreYouReturning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 那么，你现在要返回{0}吗？ 的本地化字符串。
        /// </summary>
        public static string AreYouReturningMap {
            get {
                return ResourceManager.GetString("AreYouReturningMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 射手村 的本地化字符串。
        /// </summary>
        public static string Henesys {
            get {
                return ResourceManager.GetString("Henesys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我建议你检查并确保你确实收集了#b10 #t4001101#s#k。 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_CommitTask_Fail {
            get {
                return ResourceManager.GetString("HenesysPQ_CommitTask_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 哦...这不是月兔做的年糕吗？请把年糕给我。嗯...这些看起来很美味。下次再来找我拿更多#b#t4001101##k。一路平安！ 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_CommitTask_Success {
            get {
                return ResourceManager.GetString("HenesysPQ_CommitTask_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感谢你帮助喂养兴儿。事实上，你们团队已经因走到这一步而获得了奖励。这个问题现在已经解决了，但现在又出现了另一个问题，如果你感兴趣，可以找那边的 #b达尔米#k 了解信息。那么，你现在要直接返回射手村吗？ 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_Complete {
            get {
                return ResourceManager.GetString("HenesysPQ_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #e#b&lt;组队任务: 迎月花山丘&gt;
        ///#k#n{0}
        ///
        ///我是达尔利。这里有一座美丽的山丘，迎月花在那里盛开。山丘上住着一只老虎，名叫兴儿，它似乎在找吃的。你想前往迎月花山丘，与你的队友们联手帮助兴儿吗？#b 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_Description {
            get {
                return ResourceManager.GetString("HenesysPQ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 嗨！我是达尔利。这个地方笼罩着满月的神秘气息，任何人都不能独自进入这里。 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_EnterTalk1 {
            get {
                return ResourceManager.GetString("HenesysPQ_EnterTalk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月妙组队任务遇到了错误。 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_Error {
            get {
                return ResourceManager.GetString("HenesysPQ_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #e#b&lt;组队任务: 迎月花山丘&gt;#k#n
        ///从地图底部的花朵上收集迎月花种子，然后把它们扔到上方的平台。迎月花种子的颜色必须匹配才能让种子生长，所以要不断尝试直到找到正确的组合。当所有种子都种下后，也就是任务的第二阶段开始了，在月妙为饥饿的兴儿准备年糕时进行侦查。一旦兴儿吃饱了，你的任务就完成了。 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_Intro {
            get {
                return ResourceManager.GetString("HenesysPQ_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我想兑换一件年糕的帽子。 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_Redeem {
            get {
                return ResourceManager.GetString("HenesysPQ_Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这片地方可以说是绝佳之处，每逢满月你都能品尝到月兔制作的美味年糕。 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_Tutorial0 {
            get {
                return ResourceManager.GetString("HenesysPQ_Tutorial0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在这片区域收集遍布各处的迎月花种子，然后把种子种在月牙附近的土壤里，就能看到迎月花盛开。迎月花有六种，每种都需要不同的土壤。土壤必须适合花的种子，这一点至关重要。 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_Tutorial1 {
            get {
                return ResourceManager.GetString("HenesysPQ_Tutorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当迎月花盛开时，满月就会升起，那时月兔就会出现并开始舂米。你的任务是击退怪物，确保月兔能专心制作出最美味的年糕。 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_Tutorial2 {
            get {
                return ResourceManager.GetString("HenesysPQ_Tutorial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我希望你和你的队员们合作，在规定时间内给我 10 个年糕。 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_Tutorial3 {
            get {
                return ResourceManager.GetString("HenesysPQ_Tutorial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吼！我是兴儿，时刻准备守护这片地方。你来这儿干什么？\r\n#b#L0# 请告诉我这片地方是怎么回事。#l\r\n#L1# 我带来了 #t4001101#。#l\r\n#L2# 我想离开这片地方。#l 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_TutorialTalk0 {
            get {
                return ResourceManager.GetString("HenesysPQ_TutorialTalk0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吼！我是兴儿，时刻准备守护这片地方。你来这儿干什么？\r\n#b#L0# 请告诉我这片地方是怎么回事。#l\r\n#L2# 我想离开这片地方。#l 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_TutorialTalk1 {
            get {
                return ResourceManager.GetString("HenesysPQ_TutorialTalk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 那你最好给我收集些美味的年糕，因为时间不多了，吼！ 的本地化字符串。
        /// </summary>
        public static string HenesysPQ_TutorialTalk2 {
            get {
                return ResourceManager.GetString("HenesysPQ_TutorialTalk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你希望放弃这个区域吗？ 的本地化字符串。
        /// </summary>
        public static string KerningPQ_Abandon {
            get {
                return ResourceManager.GetString("KerningPQ_Abandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #e#b&lt;组队任务：第一次合作&gt;
        ///#k#n{0}
        ///
        ///你和你的队伍成员一起完成任务怎么样？在这里，你会遇到障碍和问题，如果没有出色的团队合作，你是无法完成的。如果你想尝试，请告诉你的#b队伍领袖#k来找我谈谈。#b 的本地化字符串。
        /// </summary>
        public static string KerningPQ_Description {
            get {
                return ResourceManager.GetString("KerningPQ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 废弃都市组队任务遇到了一个错误。 的本地化字符串。
        /// </summary>
        public static string KerningPQ_Error {
            get {
                return ResourceManager.GetString("KerningPQ_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #e#b&lt;组队任务：第一次合作&gt;#k#n
        ///在完成这个组队任务的子目标时，你的队伍必须通过许多障碍和谜题。与你的团队协调合作，以便进一步前进，击败最终BOSS，并收集掉落物品以获得奖励和额外阶段的机会。 的本地化字符串。
        /// </summary>
        public static string KerningPQ_Intro {
            get {
                return ResourceManager.GetString("KerningPQ_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金币 的本地化字符串。
        /// </summary>
        public static string Meso {
            get {
                return ResourceManager.GetString("Meso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 看来你不是新手, 嗯? 那我只能收你全价了. 你想去哪儿?#b 的本地化字符串。
        /// </summary>
        public static string Npc1002000_CoditionNoviceFalse {
            get {
                return ResourceManager.GetString("Npc1002000_CoditionNoviceFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有新手都可以享受90%的特别折扣。好的，你想去哪里？#b 的本地化字符串。
        /// </summary>
        public static string Npc1002000_CoditionNoviceTrue {
            get {
                return ResourceManager.GetString("Npc1002000_CoditionNoviceTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我猜你不想待在这里了。你真的想要移动到 #b#m{0}##k 吗？好吧，这将花费你 #b{1}金币#k。你觉得怎么样？ 的本地化字符串。
        /// </summary>
        public static string Npc1002000_ConfirmMove {
            get {
                return ResourceManager.GetString("Npc1002000_ConfirmMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好的，我来为你详细介绍一下“#b魔法密林#k”。这是一座位于金银岛最东端的魔法师之城，被高耸而神秘的树木所覆盖。在这里，你还能遇到一些精灵。通常情况下，精灵们并不太喜欢人类，所以最好保持低调，不要打扰它们，努力赢得它们的好感。魔法密林是魔法师们学习魔法的圣地，这里充满了神秘与奇幻的气息，等待着勇敢的冒险家们前来探索。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Ellinia1 {
            get {
                return ResourceManager.GetString("Npc1002000_Ellinia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在魔法密林附近的森林中，你会发现绿色的史莱姆(绿水灵)、行走的蘑菇、猴子以及僵尸猴子等生物。当你深入森林时，还会遇到骑着飞天扫帚在空中飞行的女巫。不过，我要提醒你的是，除非你真的非常强大，否则我建议你最好不要靠近她们。这些女巫通常都拥有强大的魔法力量，对于实力不足的冒险家来说，可能会构成极大的威胁。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Ellinia2 {
            get {
                return ResourceManager.GetString("Npc1002000_Ellinia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果你想要成为一名#b魔法师#k，那么你需要找到#r老膜法汉斯#k，他是魔法密林的领袖。如果你的等级达到了8级或以上，并且拥有不错的智力属性，他可能会将你接纳为魔法师。但如果你还没有达到这个标准，那么你可能需要继续狩猎和训练，直到你满足要求为止。魔法师之路虽然充满挑战，但只要你拥有坚定的信念和不懈的努力，就一定能够掌握强大的魔法力量。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Ellinia3 {
            get {
                return ResourceManager.GetString("Npc1002000_Ellinia3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好的，我来为你详细介绍一下“#b射手村#k”。这是一座弓箭手之城，位于金银岛的最南端，坐落在一片广阔的平原之上，四周被茂密的森林和广袤的草原所环绕。这里的天气非常宜人，周围资源丰富，非常适合居住。射手村是弓箭手们的聚集地，他们在这里学习弓箭技巧，锻炼自己的实力。如果你对弓箭手这个职业感兴趣，不妨亲自前往射手村一探究竟。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Henesys1 {
            get {
                return ResourceManager.GetString("Npc1002000_Henesys1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在草原的周围，你会遇到一些弱小的怪物，比如蜗牛、蘑菇和猪。但据我听说，在与射手村相连的某个地方，有一个被称为“猪猪公园”的深处，那里时不时会出现一种巨大而强大的蘑菇，名叫“蘑菇王”。这个蘑菇王虽然不常出现，但一旦遇到，对于实力不足的冒险家来说可能会是一场严峻的挑战。因此，在探索猪猪公园时，一定要小心谨慎。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Henesys2 {
            get {
                return ResourceManager.GetString("Npc1002000_Henesys2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果你想要成为一名#b弓箭手#k，你需要前往射手村找到NPC“赫丽娜”。当你的等级达到或超过10级，并且拥有不错的敏捷属性时，她可能会让你成为弓箭手。但如果你还没有达到这个标准，那么你需要继续努力训练，提升自己的实力，然后再次尝试。赫丽娜是射手村的领袖之一，也是弓箭手们的导师，她会为你提供必要的指导和帮助，让你在弓箭手的道路上越来越强。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Henesys3 {
            get {
                return ResourceManager.GetString("Npc1002000_Henesys3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好的，我来为你详细介绍一下“#b废弃都市#k”。这是一座盗贼之城，位于金银岛的西北部。尽管名为“废弃都市”，但这里并非真正被遗弃，而是盗贼们的一个隐秘据点。这里的建筑物大多残破不堪，给人一种荒凉而神秘的感觉。然而，在废弃的街道上，你仍然可以发现盗贼们忙碌的身影，他们在这里交流技巧，策划行动。尽管城市上空常常笼罩着黑云，但如果你能攀登到高处，你将有机会目睹到那里独特而美丽的日落景色。废弃都市是冒险岛上一个充满挑战与机遇的地方，等待着勇敢的冒险家们前来探索。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_KerningCity1 {
            get {
                return ResourceManager.GetString("Npc1002000_KerningCity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从废弃都市出发，你可以进入多个地下城进行探险。你可以选择前往一个沼泽地带，那里鳄鱼和毒蛇遍布，充满了危险与挑战。或者，你也可以选择进入一条充满鬼魂和蝙蝠的地铁隧道，感受那阴森恐怖的氛围。而在最深处，你将遇到名为“多尔”的怪物，它的体型庞大，危险程度丝毫不亚于巨龙，是林中之城最强大的存在之一。这些地下城都充满了未知与危险，只有勇敢的冒险家才能深入其中，揭开它们的秘密。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_KerningCity2 {
            get {
                return ResourceManager.GetString("Npc1002000_KerningCity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当然，如果你想要成为一名#b飞侠#k，你需要前往废弃都市寻找#r达克鲁#k。他是这座城市黑暗之心的主宰，掌握着成为飞侠的秘密。如果你的等级达到了10级或以上，并且拥有足够的敏捷属性（DEX），他可能会认可你的潜力，让你踏上飞侠之路。但如果你还没有达到这个标准，那么你需要继续外出狩猎，锻炼自己的技能，提升自己的实力，直到你满足条件为止。飞侠之路充满了挑战与机遇，只有勇敢且机敏的冒险家才能在这条路上走得更远。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_KerningCity3 {
            get {
                return ResourceManager.GetString("Npc1002000_KerningCity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你所在的城镇是明珠港！好的，我会为你详细介绍一下#b明珠港#k。明珠港是你乘坐维多利亚号登陆金银岛的地方。很多刚从彩虹岛来到这里的新手都会在这里开始他们的旅程。这个小镇为新手提供了许多便利和指引，帮助他们熟悉游戏世界，并踏上冒险的旅途。在这里，你可以接取任务、学习技能、购买装备，为接下来的旅程做好准备 的本地化字符串。
        /// </summary>
        public static string Npc1002000_LithHarbor1 {
            get {
                return ResourceManager.GetString("Npc1002000_LithHarbor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是一个宁静的小镇，背后是宽阔的水域，这要归功于港口位于岛屿的西端。这里的大多数人都是或者曾经是渔民，因此他们可能看起来有些令人畏惧，但如果你主动与他们交谈，他们会变得非常友好。这些渔民们经历了海上的风雨，有着丰富的故事和经验，他们乐于与新来的人分享自己的生活和见闻。在明珠港，你可以感受到一种淳朴而热情的氛围，这里的人们都乐于助人，愿意为需要帮助的人伸出援手。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_LithHarbor2 {
            get {
                return ResourceManager.GetString("Npc1002000_LithHarbor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 镇子周围是一片广袤而美丽的草原。这里的怪物大多体型小巧且性格温顺，对于初来乍到的新手冒险家来说，是绝佳的练级场所。如果你还未决定自己的职业方向，那么这片草原将是你快速提升等级、熟悉游戏机制的好地方。在这里，你可以轻松击败怪物，积累经验值，同时还有机会获得丰厚的奖励，为你的冒险之旅打下坚实的基础。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_LithHarbor3 {
            get {
                return ResourceManager.GetString("Npc1002000_LithHarbor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的金币不够。以你的能力来说，不该只挣这么点！ 的本地化字符串。
        /// </summary>
        public static string Npc1002000_MesoNotEnough {
            get {
                return ResourceManager.GetString("Npc1002000_MesoNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你想去其他城镇吗？只要一点钱，我就可以安排。虽然有点贵，但我给新手提供90%的特别折扣。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Message0 {
            get {
                return ResourceManager.GetString("Npc1002000_Message0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个城镇有很多值得一看的地方。如果你想去别的地方，告诉我一声。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Message1 {
            get {
                return ResourceManager.GetString("Npc1002000_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果这是你第一次来到这个地方，可能会对这里感到困惑，有任何问题尽管问吧。\r\n#L0##b金银岛上有哪些城镇？#l\r\n#L1#请带我去别的地方。#k#l 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Message2 {
            get {
                return ResourceManager.GetString("Npc1002000_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金银岛中存在7大主城区域. 你想了解哪一个?#b 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Message3 {
            get {
                return ResourceManager.GetString("Npc1002000_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #m120000000#它是一艘停泊在金银岛魔法密林与手村之间的潜水艇。这艘潜水艇是众多海盗的家园，他们在这里过着海上漂泊的生活。在潜水艇上，你可以欣赏到与明珠同样美丽的海洋风光。虽然身处海底，但透过潜水艇的窗户，你依然能感受到大海的壮阔与宁静。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Nautilus1 {
            get {
                return ResourceManager.GetString("Npc1002000_Nautilus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #m120000000#停泊在射手村和埃琳娜之间，所以如果你稍微走出去一点，就能同时欣赏到两个城镇的景色。镇上的海盗们都非常热情友好。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Nautilus2 {
            get {
                return ResourceManager.GetString("Npc1002000_Nautilus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果你真的想成为一名#b海盗#k，那么你最好去见见#m120000000#的船长，#r#p1090000##k。如果你的等级超过10级，并且敏捷属性（DEX）达到20，那么她可能会让你成为海盗。如果你还没有达到这个水平，那么你需要更加努力训练，直到你达到要求！ 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Nautilus3 {
            get {
                return ResourceManager.GetString("Npc1002000_Nautilus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好的，我会为你详细介绍一下“#b勇士部落#k”。它是一座位于金银岛最北端的战士之城，四周环绕着险峻的岩石山脉。这里的气氛并不友善，生存条件极为苛刻，只有真正的强者才能在这里生存下来。勇士部落是战士们的试炼场，他们在这里接受最严酷的挑战，锤炼自己的意志和技艺，以追求更高的荣耀和力量。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Perion1 {
            get {
                return ResourceManager.GetString("Npc1002000_Perion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在这片高地周围，你会发现一棵异常瘦削的树，一只野猪在四处奔跑，还有猴子遍布整个岛屿。此外，这里还隐藏着一个深邃的山谷。当你深入其中时，会遇到一头体型庞大的巨龙，它的力量与其体型相称，令人畏惧。因此，进入这个山谷时一定要格外小心，或者干脆避免前往，以免遭遇不测。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Perion2 {
            get {
                return ResourceManager.GetString("Npc1002000_Perion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果你想要成为一名#b战士#k，那么你需要找到#r武术教练#k，也就是勇士部落的首领。如果你的等级达到了10级或以上，并且拥有不错的力量属性，他可能会将你接纳为战士。但如果你还没有达到这个标准，那么最好继续努力训练，直到你满足要求为止。战士之路充满挑战，但只要你坚持不懈，就一定能够成为真正的勇士。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Perion3 {
            get {
                return ResourceManager.GetString("Npc1002000_Perion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好的，我来给你详细介绍一下#b林中之城#k。这是一个位于金银岛东南部的森林小镇，大致位于射手村和蚂蚁洞窟之间。镇上有一家旅馆，所以你可以在地下城探险一整天后去那里休息。总的来说，这是一个安静的小镇。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Sleepywood1 {
            get {
                return ResourceManager.GetString("Npc1002000_Sleepywood1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在旅馆前面，有一位名叫#r克里斯拉玛#k的老和尚。关于这位和尚，没有人知道太多。据说他会从旅行者那里收集材料并制作一些东西，但我不太清楚具体细节。如果你在那个地区有任何事情要做，请帮我查一下 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Sleepywood2 {
            get {
                return ResourceManager.GetString("Npc1002000_Sleepywood2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从林中之城出发，向东走，你会发现通往金银岛最深处的蚂蚁隧道。那里有很多恶心且强大的怪物，所以如果你以为这只是散步那么简单，那你可能会以尸体的形式出来。在进去之前，你需要做好充分的准备，迎接一场艰难的旅程。 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Sleepywood3 {
            get {
                return ResourceManager.GetString("Npc1002000_Sleepywood3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是我听说的……据说在林中之城有一个秘密入口，通往一个未知的地方。据说，一旦你深入其中，你会发现一堆会移动的黑石。我近期想亲眼看看那到底是什么…… 的本地化字符串。
        /// </summary>
        public static string Npc1002000_Sleepywood4 {
            get {
                return ResourceManager.GetString("Npc1002000_Sleepywood4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经有人在尝试这个组队任务了。请等待他们完成，或者寻找其他频道。 的本地化字符串。
        /// </summary>
        public static string PartyQuest_CannotStart_ChannelFull {
            get {
                return ResourceManager.GetString("PartyQuest_CannotStart_ChannelFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有当你加入一个队伍时，你才能参加组队任务。 的本地化字符串。
        /// </summary>
        public static string PartyQuest_CannotStart_Party {
            get {
                return ResourceManager.GetString("PartyQuest_CannotStart_Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你还不能开始这个组队任务，因为你的队伍人数可能不在规定范围内，或者你的一些队员不符合参与条件，又或者他们不在这个地图里。 的本地化字符串。
        /// </summary>
        public static string PartyQuest_CannotStart_Req {
            get {
                return ResourceManager.GetString("PartyQuest_CannotStart_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我想了解更多详情。 的本地化字符串。
        /// </summary>
        public static string PartyQuest_Intro {
            get {
                return ResourceManager.GetString("PartyQuest_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果你想进入这里，必须由你的队长和我交谈。和你的队长说一下这件事。 的本地化字符串。
        /// </summary>
        public static string PartyQuest_NeedLeaderTalk {
            get {
                return ResourceManager.GetString("PartyQuest_NeedLeaderTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我想参加组队任务。 的本地化字符串。
        /// </summary>
        public static string PartyQuest_Participate {
            get {
                return ResourceManager.GetString("PartyQuest_Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///   组队人数：{0}
        ///   等级要求：{1} 
        ///   时间限制：{2} 分钟 的本地化字符串。
        /// </summary>
        public static string PartyQuest_Requirement {
            get {
                return ResourceManager.GetString("PartyQuest_Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 看起来你的某个背包空间不足。请先检查一下，以便正确获得奖励。 的本地化字符串。
        /// </summary>
        public static string Redeem_InventoryFull {
            get {
                return ResourceManager.GetString("Redeem_InventoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你还没有足够的 {0} 来兑换它！ 的本地化字符串。
        /// </summary>
        public static string Redeem_NotEnough {
            get {
                return ResourceManager.GetString("Redeem_NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给你。尽情享用！ 的本地化字符串。
        /// </summary>
        public static string Redeem_Success {
            get {
                return ResourceManager.GetString("Redeem_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确保你的#r奖品仓库#k中至少有{0}个空位。 的本地化字符串。
        /// </summary>
        public static string Storage_CheckGachaponStorage {
            get {
                return ResourceManager.GetString("Storage_CheckGachaponStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确保你有 #i{0}##b#t{0}#x{1}#k。 的本地化字符串。
        /// </summary>
        public static string Tip_CheckItemWithId {
            get {
                return ResourceManager.GetString("Tip_CheckItemWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你得到了 #b#t{0}##k。 的本地化字符串。
        /// </summary>
        public static string Tip_ObtainItem {
            get {
                return ResourceManager.GetString("Tip_ObtainItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谢谢惠顾 的本地化字符串。
        /// </summary>
        public static string Tip_ThankPatronage {
            get {
                return ResourceManager.GetString("Tip_ThankPatronage", resourceCulture);
            }
        }
    }
}
