//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Messages.SystemMessage", typeof(SystemMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}]已启动 的本地化字符串。
        /// </summary>
        public static string Server_Active {
            get {
                return ResourceManager.GetString("Server_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}] 所有频道已停止 的本地化字符串。
        /// </summary>
        public static string Server_AllChannelShutdown {
            get {
                return ResourceManager.GetString("Server_AllChannelShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}]未启动 的本地化字符串。
        /// </summary>
        public static string Server_InActive {
            get {
                return ResourceManager.GetString("Server_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}] 正在保存玩家数据...完成 的本地化字符串。
        /// </summary>
        public static string Server_SaveUserDataComplete {
            get {
                return ResourceManager.GetString("Server_SaveUserDataComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}] 正在保存玩家数据... 的本地化字符串。
        /// </summary>
        public static string Server_SaveUserDataStart {
            get {
                return ResourceManager.GetString("Server_SaveUserDataStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}] 正在停止...完成 的本地化字符串。
        /// </summary>
        public static string Server_ShutdownComplete {
            get {
                return ResourceManager.GetString("Server_ShutdownComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}] 正在停止... 的本地化字符串。
        /// </summary>
        public static string Server_Shutingdown {
            get {
                return ResourceManager.GetString("Server_Shutingdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}] 启动中... 的本地化字符串。
        /// </summary>
        public static string Server_Start {
            get {
                return ResourceManager.GetString("Server_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}] 启动{Status} 的本地化字符串。
        /// </summary>
        public static string Server_StartFailed {
            get {
                return ResourceManager.GetString("Server_StartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}] 启动{Status}, 监听端口{Port} 的本地化字符串。
        /// </summary>
        public static string Server_StartSuccess {
            get {
                return ResourceManager.GetString("Server_StartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}] 停止监听...完成 的本地化字符串。
        /// </summary>
        public static string Server_StopListenComplete {
            get {
                return ResourceManager.GetString("Server_StopListenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ServerName}] 停止监听... 的本地化字符串。
        /// </summary>
        public static string Server_StopListenStart {
            get {
                return ResourceManager.GetString("Server_StopListenStart", resourceCulture);
            }
        }
    }
}
