syntax = "proto3";

package ProtoModel;



message NewYearCardProto {
	int32 id = 1;
	int32 senderId = 2;
	int32 receiverId = 3;
	string message = 4;
	string senderName = 5;
	string receiverName = 6;
	bool senderDiscard = 7;
	bool receiverDiscard = 8;
	bool received = 9;
	int64 timeSent = 10;
	int64 timeReceived = 11;
}



message NewYearCardNotifyProto {
	repeated NewYearCardNotifyItemProto list = 1;
}



message NewYearCardNotifyItemProto {
	int32 masterId = 1;
	repeated NewYearCardProto list = 2;
}
