using Application.Shared.Constants.Item;

namespace Application.Module.Marriage.Common.Models
{
    public enum WeddingItem
    {
        WR_MOONSTONE = ItemId.WEDDING_RING_MOONSTONE, // Wedding Ring
        WR_STARGEM = ItemId.WEDDING_RING_STAR,
        WR_GOLDENHEART = ItemId.WEDDING_RING_GOLDEN,
        WR_SILVERSWAN = ItemId.WEDDING_RING_SILVER,
        ERB_MOONSTONE = ItemId.ENGAGEMENT_BOX_MOONSTONE, // Engagement Ring Box
        ERB_STARGEM = ItemId.ENGAGEMENT_BOX_STAR,
        ERB_GOLDENHEART = ItemId.ENGAGEMENT_BOX_GOLDEN,
        ERB_SILVERSWAN = ItemId.ENGAGEMENT_BOX_SILVER,
        ERBE_MOONSTONE = ItemId.EMPTY_ENGAGEMENT_BOX_MOONSTONE, // Engagement Ring Box (Empty)
        ER_MOONSTONE = ItemId.ENGAGEMENT_RING_MOONSTONE, // Engagement Ring
        ERBE_STARGEM = ItemId.EMPTY_ENGAGEMENT_BOX_STAR,
        ER_STARGEM = ItemId.ENGAGEMENT_RING_STAR,
        ERBE_GOLDENHEART = ItemId.EMPTY_ENGAGEMENT_BOX_GOLDEN,
        ER_GOLDENHEART = ItemId.ENGAGEMENT_RING_GOLDEN,
        ERBE_SILVERSWAN = ItemId.EMPTY_ENGAGEMENT_BOX_SILVER,
        ER_SILVERSWAN = ItemId.ENGAGEMENT_RING_SILVER,
        PARENTS_BLESSING = ItemId.PARENTS_BLESSING, // Parents Blessing
        OFFICIATORS_PERMISSION = ItemId.OFFICIATORS_PERMISSION, // Officiator's Permission
        WR_CATHEDRAL_PREMIUM = ItemId.PREMIUM_CATHEDRAL_RESERVATION_RECEIPT, // Wedding Ring?
        WR_VEGAS_PREMIUM = ItemId.PREMIUM_CHAPEL_RESERVATION_RECEIPT,
        IB_VEGAS = ItemId.INVITATION_CHAPEL,      // toSend invitation
        IB_CATHEDRAL = ItemId.INVITATION_CATHEDRAL,  // toSend invitation
        IG_VEGAS = ItemId.RECEIVED_INVITATION_CHAPEL,      // rcvd invitation
        IG_CATHEDRAL = ItemId.RECEIVED_INVITATION_CATHEDRAL,  // rcvd invitation
        OB_FORCOUPLE = ItemId.ONYX_CHEST_FOR_COUPLE, // Onyx Box? For Couple
        WR_CATHEDRAL_NORMAL = ItemId.NORMAL_CATHEDRAL_RESERVATION_RECEIPT, // Wedding Ring?
        WR_VEGAS_NORMAL = ItemId.NORMAL_CHAPEL_RESERVATION_RECEIPT,
        WT_CATHEDRAL_NORMAL = ItemId.NORMAL_WEDDING_TICKET_CATHEDRAL, // Wedding Ticket
        WT_VEGAS_NORMAL = ItemId.NORMAL_WEDDING_TICKET_CHAPEL,
        WT_VEGAS_PREMIUM = ItemId.PREMIUM_WEDDING_TICKET_CHAPEL,
        WT_CATHEDRAL_PREMIUM = ItemId.PREMIUM_WEDDING_TICKET_CATHEDRAL
    }
}
