// <auto-generated />
using System;
using Application.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Core.EF.Sqlite.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260724090122_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Application.Core.EF.Entities.AccountBanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    b.Property<int>("BanLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("EndTime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Reason")
                        .HasColumnType("tinyint")
                        .HasColumnName("Reason");

                    b.Property<string>("ReasonDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ReasonDescription");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("StartTime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccountId" }, "accountid");

                    b.ToTable("account_ban", (string)null);
                });

            modelBuilder.Entity("Application.Core.EF.Entities.ExpLogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CharId")
                        .HasColumnType("int")
                        .HasColumnName("charid");

                    b.Property<int>("CurrentExp")
                        .HasColumnType("int")
                        .HasColumnName("current_exp");

                    b.Property<float>("ExpCoupon")
                        .HasColumnType("int")
                        .HasColumnName("exp_coupon");

                    b.Property<DateTime>("ExpGainTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("exp_gain_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("GainedExp")
                        .HasColumnType("bigint")
                        .HasColumnName("gained_exp");

                    b.Property<float>("WorldExpRate")
                        .HasColumnType("int")
                        .HasColumnName("world_exp_rate");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("characterexplogs", (string)null);
                });

            modelBuilder.Entity("Application.Core.EF.Entities.Gachapons.GachaponPoolEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("''");

                    b.Property<int>("NpcId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("sys_gachapon_pool", (string)null);
                });

            modelBuilder.Entity("Application.Core.EF.Entities.Gachapons.GachaponPoolItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("sys_gachapon_pool_item", (string)null);
                });

            modelBuilder.Entity("Application.Core.EF.Entities.Gachapons.GachaponPoolLevelChanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("sys_gachapon_pool_level_chance", (string)null);
                });

            modelBuilder.Entity("Application.EF.CdkCodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<long>("Expiration")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "idx_code")
                        .IsUnique();

                    b.ToTable("cdk_codes", (string)null);
                });

            modelBuilder.Entity("Application.EF.CdkRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecipientTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CodeId" }, "idx_code")
                        .HasDatabaseName("idx_code1");

                    b.ToTable("cdk_records", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.AccountBindingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    b.Property<string>("HWID")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("HWID")
                        .HasDefaultValueSql("''");

                    b.Property<string>("IP")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("IP")
                        .HasDefaultValueSql("''");

                    b.Property<DateTime>("LastActiveTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("LastActiveTime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("MAC")
                        .HasDefaultValueSql("''");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccountId" }, "accountid")
                        .HasDatabaseName("accountid1");

                    b.ToTable("account_bindings", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Birthday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("birthday")
                        .HasDefaultValueSql("'2005-05-11'");

                    b.Property<byte[]>("Blob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<sbyte>("Characterslots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("characterslots")
                        .HasDefaultValueSql("'3'");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<sbyte>("GMLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("gmlevel")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("gender")
                        .HasDefaultValueSql("'10'");

                    b.Property<int>("MaplePoint")
                        .HasColumnType("int")
                        .HasColumnName("maplePoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Nick")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("nick");

                    b.Property<int>("NxCredit")
                        .HasColumnType("int")
                        .HasColumnName("nxCredit");

                    b.Property<int>("NxPrepaid")
                        .HasColumnType("int")
                        .HasColumnName("nxPrepaid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("password")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Pic")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("pic")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("pin")
                        .HasDefaultValueSql("''");

                    b.Property<bool>("Tos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tos");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id", "Name" }, "id");

                    b.HasIndex(new[] { "Id", "NxCredit", "MaplePoint", "NxPrepaid" }, "id_2");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.AllianceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity")
                        .HasDefaultValueSql("'2'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notice")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("notice")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Rank1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("rank1")
                        .HasDefaultValueSql("'Master'");

                    b.Property<string>("Rank2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("rank2")
                        .HasDefaultValueSql("'Jr. Master'");

                    b.Property<string>("Rank3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("rank3")
                        .HasDefaultValueSql("'Member'");

                    b.Property<string>("Rank4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("rank4")
                        .HasDefaultValueSql("'Member'");

                    b.Property<string>("Rank5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("rank5")
                        .HasDefaultValueSql("'Member'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "name")
                        .HasDatabaseName("name1");

                    b.ToTable("alliance", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.BbsReplyEntity", b =>
                {
                    b.Property<int>("Replyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("replyid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("content")
                        .HasDefaultValueSql("''");

                    b.Property<int>("Postercid")
                        .HasColumnType("int")
                        .HasColumnName("postercid");

                    b.Property<int>("Threadid")
                        .HasColumnType("int")
                        .HasColumnName("threadid");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.HasKey("Replyid")
                        .HasName("PRIMARY");

                    b.ToTable("bbs_replies", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.BbsThreadEntity", b =>
                {
                    b.Property<int>("Threadid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("threadid");

                    b.Property<int>("Guildid")
                        .HasColumnType("int")
                        .HasColumnName("guildid");

                    b.Property<short>("Icon")
                        .HasColumnType("smallint")
                        .HasColumnName("icon");

                    b.Property<int>("Localthreadid")
                        .HasColumnType("int")
                        .HasColumnName("localthreadid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasDefaultValueSql("''");

                    b.Property<int>("Postercid")
                        .HasColumnType("int")
                        .HasColumnName("postercid");

                    b.Property<short>("Replycount")
                        .HasColumnType("smallint")
                        .HasColumnName("replycount");

                    b.Property<string>("Startpost")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("startpost");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.HasKey("Threadid")
                        .HasName("PRIMARY");

                    b.ToTable("bbs_threads", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.BosslogDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Attempttime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("attempttime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Bosstype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bosstype");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("characterid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("bosslog_daily", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.BosslogWeekly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Attempttime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("attempttime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Bosstype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bosstype");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("characterid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("bosslog_weekly", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.CdkItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'4000000'");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'5'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CodeId" }, "idx_code")
                        .HasDatabaseName("idx_code2");

                    b.ToTable("cdk_items", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.CharacterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("accountid");

                    b.Property<int>("AllianceRank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("allianceRank")
                        .HasDefaultValueSql("'5'");

                    b.Property<int>("Ap")
                        .HasColumnType("int")
                        .HasColumnName("ap");

                    b.Property<int>("AriantPoints")
                        .HasColumnType("int")
                        .HasColumnName("ariantPoints");

                    b.Property<byte[]>("Blob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("BuddyCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("buddyCapacity")
                        .HasDefaultValueSql("'25'");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("createdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DataString")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("dataString")
                        .HasDefaultValueSql("''");

                    b.Property<int>("Dex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dex")
                        .HasDefaultValueSql("'5'");

                    b.Property<int>("DojoPoints")
                        .HasColumnType("int")
                        .HasColumnName("dojoPoints");

                    b.Property<int>("Equipslots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equipslots")
                        .HasDefaultValueSql("'24'");

                    b.Property<int>("Etcslots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("etcslots")
                        .HasDefaultValueSql("'24'");

                    b.Property<int>("Exp")
                        .HasColumnType("int")
                        .HasColumnName("exp");

                    b.Property<int>("Face")
                        .HasColumnType("int")
                        .HasColumnName("face");

                    b.Property<int>("Fame")
                        .HasColumnType("int")
                        .HasColumnName("fame");

                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("familyId")
                        .HasDefaultValueSql("'-1'");

                    b.Property<bool>("FinishedDojoTutorial")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("finishedDojoTutorial");

                    b.Property<int>("Fquest")
                        .HasColumnType("int")
                        .HasColumnName("fquest");

                    b.Property<int>("Gachaexp")
                        .HasColumnType("int")
                        .HasColumnName("gachaexp");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<int>("GuildId")
                        .HasColumnType("int")
                        .HasColumnName("guildid");

                    b.Property<int>("GuildRank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("guildrank")
                        .HasDefaultValueSql("'5'");

                    b.Property<int>("Hair")
                        .HasColumnType("int")
                        .HasColumnName("hair");

                    b.Property<int>("Hp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hp")
                        .HasDefaultValueSql("'50'");

                    b.Property<int>("HpAlert")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HpMpUsed")
                        .HasColumnType("int")
                        .HasColumnName("hpMpUsed");

                    b.Property<int>("Int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("int")
                        .HasDefaultValueSql("'4'");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<long>("Jailexpire")
                        .HasColumnType("bigint")
                        .HasColumnName("jailexpire");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job");

                    b.Property<int>("JobRank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("jobRank")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("JobRankMove")
                        .HasColumnType("int")
                        .HasColumnName("jobRankMove");

                    b.Property<int>("LastDojoStage")
                        .HasColumnType("int")
                        .HasColumnName("lastDojoStage");

                    b.Property<DateTime>("LastExpGainTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("lastExpGainTime")
                        .HasDefaultValueSql("'2015-01-01 05:00:00'");

                    b.Property<DateTime>("LastLogoutTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("lastLogoutTime")
                        .HasDefaultValueSql("'2015-01-01 05:00:00'");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("level")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("Luk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("luk")
                        .HasDefaultValueSql("'4'");

                    b.Property<int>("Map")
                        .HasColumnType("int")
                        .HasColumnName("map");

                    b.Property<int>("Matchcardlosses")
                        .HasColumnType("int")
                        .HasColumnName("matchcardlosses");

                    b.Property<int>("Matchcardties")
                        .HasColumnType("int")
                        .HasColumnName("matchcardties");

                    b.Property<int>("Matchcardwins")
                        .HasColumnType("int")
                        .HasColumnName("matchcardwins");

                    b.Property<int>("Maxhp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maxhp")
                        .HasDefaultValueSql("'50'");

                    b.Property<int>("Maxmp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maxmp")
                        .HasDefaultValueSql("'5'");

                    b.Property<int>("Meso")
                        .HasColumnType("int")
                        .HasColumnName("meso");

                    b.Property<int>("Monsterbookcover")
                        .HasColumnType("int")
                        .HasColumnName("monsterbookcover");

                    b.Property<int>("MountExp")
                        .HasColumnType("int")
                        .HasColumnName("mountexp");

                    b.Property<int>("MountLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mountlevel")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("Mounttiredness")
                        .HasColumnType("int")
                        .HasColumnName("mounttiredness");

                    b.Property<int>("Mp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mp")
                        .HasDefaultValueSql("'5'");

                    b.Property<int>("MpAlert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasDefaultValueSql("''");

                    b.Property<int>("Omoklosses")
                        .HasColumnType("int")
                        .HasColumnName("omoklosses");

                    b.Property<int>("Omokties")
                        .HasColumnType("int")
                        .HasColumnName("omokties");

                    b.Property<int>("Omokwins")
                        .HasColumnType("int")
                        .HasColumnName("omokwins");

                    b.Property<bool>("PartySearch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("partySearch");

                    b.Property<int>("Pqpoints")
                        .HasColumnType("int")
                        .HasColumnName("PQPoints");

                    b.Property<int>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rank")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("RankMove")
                        .HasColumnType("int")
                        .HasColumnName("rankMove");

                    b.Property<int>("Setupslots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("setupslots")
                        .HasDefaultValueSql("'24'");

                    b.Property<int>("Skincolor")
                        .HasColumnType("int")
                        .HasColumnName("skincolor");

                    b.Property<string>("Sp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("sp")
                        .HasDefaultValueSql("'0,0,0,0,0,0,0,0,0,0'");

                    b.Property<int>("Spawnpoint")
                        .HasColumnType("int")
                        .HasColumnName("spawnpoint");

                    b.Property<int>("Str")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("str")
                        .HasDefaultValueSql("'12'");

                    b.Property<int>("SummonValue")
                        .HasColumnType("int")
                        .HasColumnName("summonValue");

                    b.Property<int>("Useslots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("useslots")
                        .HasDefaultValueSql("'24'");

                    b.Property<int>("VanquisherKills")
                        .HasColumnType("int")
                        .HasColumnName("vanquisherKills");

                    b.Property<int>("VanquisherStage")
                        .HasColumnType("int")
                        .HasColumnName("vanquisherStage");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccountId" }, "accountid")
                        .HasDatabaseName("accountid2");

                    b.HasIndex(new[] { "Id", "AccountId", "Name" }, "id_2")
                        .HasDatabaseName("id_21");

                    b.HasIndex(new[] { "Level", "Exp" }, "ranking1");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.DropDataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Chance")
                        .HasColumnType("int")
                        .HasColumnName("chance");

                    b.Property<int>("Dropperid")
                        .HasColumnType("int")
                        .HasColumnName("dropperid");

                    b.Property<int>("Itemid")
                        .HasColumnType("int")
                        .HasColumnName("itemid");

                    b.Property<int>("MaximumQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maximum_quantity")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("MinimumQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("minimum_quantity")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("Questid")
                        .HasColumnType("int")
                        .HasColumnName("questid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Dropperid", "Itemid" }, "dropperid")
                        .IsUnique();

                    b.HasIndex(new[] { "Dropperid", "Itemid" }, "dropperid_2");

                    b.HasIndex(new[] { "Dropperid" }, "mobid");

                    b.ToTable("sys_drop_data", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.DropDataGlobal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Chance")
                        .HasColumnType("int")
                        .HasColumnName("chance");

                    b.Property<string>("Comments")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("comments");

                    b.Property<sbyte>("Continent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("continent")
                        .HasDefaultValueSql("'-1'");

                    b.Property<int>("Itemid")
                        .HasColumnType("int")
                        .HasColumnName("itemid");

                    b.Property<int>("MaximumQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maximum_quantity")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("MinimumQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("minimum_quantity")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("Questid")
                        .HasColumnType("int")
                        .HasColumnName("questid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Continent" }, "mobid")
                        .HasDatabaseName("mobid1");

                    b.ToTable("sys_drop_data_global", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.DueyPackageEntity", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ClaimTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("'2015-01-01 05:00:00'");

                    b.Property<bool>("HasNotified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("ItemBlob")
                        .HasColumnType("BLOB");

                    b.Property<int>("Mesos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<bool>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("PackageId")
                        .HasName("PRIMARY");

                    b.ToTable("dueypackages", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.FamilyCharacterEntity", b =>
                {
                    b.Property<int>("Cid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cid");

                    b.Property<int>("Familyid")
                        .HasColumnType("int")
                        .HasColumnName("familyid");

                    b.Property<long>("Lastresettime")
                        .HasColumnType("bigint")
                        .HasColumnName("lastresettime");

                    b.Property<string>("Precepts")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("precepts");

                    b.Property<int>("Reptosenior")
                        .HasColumnType("int")
                        .HasColumnName("reptosenior");

                    b.Property<int>("Reputation")
                        .HasColumnType("int")
                        .HasColumnName("reputation");

                    b.Property<int>("Seniorid")
                        .HasColumnType("int")
                        .HasColumnName("seniorid");

                    b.Property<int>("Todaysrep")
                        .HasColumnType("int")
                        .HasColumnName("todaysrep");

                    b.Property<int>("Totalreputation")
                        .HasColumnType("int")
                        .HasColumnName("totalreputation");

                    b.HasKey("Cid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cid", "Familyid" }, "cid");

                    b.ToTable("family_character", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.FamilyEntitlementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Charid")
                        .HasColumnType("int")
                        .HasColumnName("charid");

                    b.Property<int>("Entitlementid")
                        .HasColumnType("int")
                        .HasColumnName("entitlementid");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Charid" }, "charid");

                    b.ToTable("family_entitlement", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.FredstorageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Cid")
                        .HasColumnType("int")
                        .HasColumnName("cid");

                    b.Property<int>("Daynotes")
                        .HasColumnType("int")
                        .HasColumnName("daynotes");

                    b.Property<int>("ItemMeso")
                        .HasColumnType("bigint")
                        .HasColumnName("itemMeso");

                    b.Property<byte[]>("ItemsBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Meso")
                        .HasColumnType("int")
                        .HasColumnName("meso");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cid" }, "cid_2")
                        .IsUnique();

                    b.ToTable("fredstorage", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.GiftEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("FromId")
                        .HasColumnType("int")
                        .HasColumnName("fromId");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("tinytext")
                        .HasColumnName("message");

                    b.Property<int>("RingSourceId")
                        .HasColumnType("int")
                        .HasColumnName("ringSourceId");

                    b.Property<int>("Sn")
                        .HasColumnType("int")
                        .HasColumnName("sn");

                    b.Property<int>("ToId")
                        .HasColumnType("int")
                        .HasColumnName("toId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("gifts", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.GuildEntity", b =>
                {
                    b.Property<int>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("guildid");

                    b.Property<int>("AllianceId")
                        .HasColumnType("int")
                        .HasColumnName("allianceId");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("capacity")
                        .HasDefaultValueSql("'10'");

                    b.Property<int>("GP")
                        .HasColumnType("int")
                        .HasColumnName("GP");

                    b.Property<int>("Leader")
                        .HasColumnType("int")
                        .HasColumnName("leader");

                    b.Property<int>("Logo")
                        .HasColumnType("int")
                        .HasColumnName("logo");

                    b.Property<int>("LogoBg")
                        .HasColumnType("int")
                        .HasColumnName("logoBG");

                    b.Property<short>("LogoBgColor")
                        .HasColumnType("smallint")
                        .HasColumnName("logoBGColor");

                    b.Property<short>("LogoColor")
                        .HasColumnType("smallint")
                        .HasColumnName("logoColor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notice")
                        .HasMaxLength(101)
                        .HasColumnType("TEXT")
                        .HasColumnName("notice");

                    b.Property<string>("Rank1Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("rank1title")
                        .HasDefaultValueSql("'Master'");

                    b.Property<string>("Rank2Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("rank2title")
                        .HasDefaultValueSql("'Jr. Master'");

                    b.Property<string>("Rank3Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("rank3title")
                        .HasDefaultValueSql("'Member'");

                    b.Property<string>("Rank4Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("rank4title")
                        .HasDefaultValueSql("'Member'");

                    b.Property<string>("Rank5Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("rank5title")
                        .HasDefaultValueSql("'Member'");

                    b.Property<long>("Signature")
                        .HasColumnType("int")
                        .HasColumnName("signature");

                    b.HasKey("GuildId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GuildId", "Name" }, "guildid");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.Hwidaccount", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accountid");

                    b.Property<string>("Hwid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("hwid")
                        .HasDefaultValueSql("''");

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("expiresat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<sbyte>("Relevance")
                        .HasColumnType("tinyint")
                        .HasColumnName("relevance");

                    b.HasKey("AccountId", "Hwid")
                        .HasName("PRIMARY");

                    b.ToTable("hwidaccounts", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.HwidbanEntity", b =>
                {
                    b.Property<int>("Hwidbanid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("hwidbanid");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AccountId");

                    b.Property<string>("Hwid")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("hwid");

                    b.HasKey("Hwidbanid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Hwid" }, "hwid_2")
                        .IsUnique();

                    b.ToTable("hwidbans", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.IpbanEntity", b =>
                {
                    b.Property<int>("Ipbanid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ipbanid");

                    b.Property<int>("Aid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aid");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip")
                        .HasDefaultValueSql("''");

                    b.HasKey("Ipbanid")
                        .HasName("PRIMARY");

                    b.ToTable("ipbans", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.MacbanEntity", b =>
                {
                    b.Property<int>("Macbanid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("macbanid");

                    b.Property<int>("Aid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aid");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("mac");

                    b.HasKey("Macbanid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Mac" }, "mac_2")
                        .IsUnique();

                    b.ToTable("macbans", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.MarriageEntity", b =>
                {
                    b.Property<int>("Marriageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("marriageid");

                    b.Property<int>("EngagementItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Husbandid")
                        .HasColumnType("int")
                        .HasColumnName("husbandid");

                    b.Property<int>("RingSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time0")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Time1")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Time2")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wifeid")
                        .HasColumnType("int")
                        .HasColumnName("wifeid");

                    b.HasKey("Marriageid")
                        .HasName("PRIMARY");

                    b.ToTable("marriages", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.MonsterCardDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Cardid")
                        .HasColumnType("int")
                        .HasColumnName("cardid");

                    b.Property<int>("Mobid")
                        .HasColumnType("int")
                        .HasColumnName("mobid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id1");

                    b.ToTable("sys_monstercarddata", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.MtsCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Cid")
                        .HasColumnType("int")
                        .HasColumnName("cid");

                    b.Property<int>("Itemid")
                        .HasColumnType("int")
                        .HasColumnName("itemid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("mts_cart", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.MtsItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Acc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("acc")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Avoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("avoid")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("BidIncre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bid_incre")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("BuyNow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("buy_now")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Dex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dex")
                        .HasDefaultValueSql("'0'");

                    b.Property<long>("Expiration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("expiration")
                        .HasDefaultValueSql("'-1'");

                    b.Property<int>("Flag")
                        .HasColumnType("int")
                        .HasColumnName("flag");

                    b.Property<string>("GiftFrom")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("giftFrom");

                    b.Property<int>("Hands")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hands")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Hp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hp")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("int")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Isequip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("isequip")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Itemexp")
                        .HasColumnType("int")
                        .HasColumnName("itemexp");

                    b.Property<int>("Itemid")
                        .HasColumnType("int")
                        .HasColumnName("itemid");

                    b.Property<int>("Itemlevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("itemlevel")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("Jump")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("jump")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("level")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Locked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("locked")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Luk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("luk")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Matk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("matk")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Mdef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mdef")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Mp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mp")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner")
                        .HasDefaultValueSql("''");

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("position")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quantity")
                        .HasDefaultValueSql("'1'");

                    b.Property<long>("Ringid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ringid")
                        .HasDefaultValueSql("'-1'");

                    b.Property<string>("SellEnds")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("sell_ends");

                    b.Property<int>("Seller")
                        .HasColumnType("int")
                        .HasColumnName("seller");

                    b.Property<string>("Sellername")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("sellername");

                    b.Property<int>("Speed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("speed")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Str")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("str")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Tab")
                        .HasColumnType("int")
                        .HasColumnName("tab");

                    b.Property<int>("Transfer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transfer")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<int>("Upgradeslots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("upgradeslots")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Vicious")
                        .HasColumnType("int")
                        .HasColumnName("vicious");

                    b.Property<int>("Watk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("watk")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Wdef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wdef")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("mts_items", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.Namechange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Characterid")
                        .HasColumnType("int")
                        .HasColumnName("characterid");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("completionTime");

                    b.Property<string>("New")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("new");

                    b.Property<string>("Old")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("old");

                    b.Property<DateTime>("RequestTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("requestTime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Characterid" }, "characterid");

                    b.ToTable("namechanges", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.PlayerNpcEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Cy")
                        .HasColumnType("int")
                        .HasColumnName("cy");

                    b.Property<int>("Dir")
                        .HasColumnType("int")
                        .HasColumnName("dir");

                    b.Property<int>("Face")
                        .HasColumnType("int")
                        .HasColumnName("face");

                    b.Property<int>("Fh")
                        .HasColumnType("int")
                        .HasColumnName("fh");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<int>("Hair")
                        .HasColumnType("int")
                        .HasColumnName("hair");

                    b.Property<int>("Job")
                        .HasColumnType("int")
                        .HasColumnName("job");

                    b.Property<int>("Map")
                        .HasColumnType("int")
                        .HasColumnName("map");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Overallrank")
                        .HasColumnType("int")
                        .HasColumnName("overallrank");

                    b.Property<int>("Rx0")
                        .HasColumnType("int")
                        .HasColumnName("rx0");

                    b.Property<int>("Rx1")
                        .HasColumnType("int")
                        .HasColumnName("rx1");

                    b.Property<int>("Scriptid")
                        .HasColumnType("int")
                        .HasColumnName("scriptid");

                    b.Property<int>("Skin")
                        .HasColumnType("int")
                        .HasColumnName("skin");

                    b.Property<int>("World")
                        .HasColumnType("int")
                        .HasColumnName("world");

                    b.Property<int>("Worldjobrank")
                        .HasColumnType("int")
                        .HasColumnName("worldjobrank");

                    b.Property<int>("Worldrank")
                        .HasColumnType("int")
                        .HasColumnName("worldrank");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("x");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("playernpcs", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.PlayerNpcsEquipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Equipid")
                        .HasColumnType("int")
                        .HasColumnName("equipid");

                    b.Property<int>("Equippos")
                        .HasColumnType("int")
                        .HasColumnName("equippos");

                    b.Property<int>("Npcid")
                        .HasColumnType("int")
                        .HasColumnName("npcid");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("playernpcs_equip", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.PlayernpcsField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Map")
                        .HasColumnType("int")
                        .HasColumnName("map");

                    b.Property<short>("Podium")
                        .HasColumnType("smallint")
                        .HasColumnName("podium");

                    b.Property<sbyte>("Step")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("step")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("World")
                        .HasColumnType("int")
                        .HasColumnName("world");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("playernpcs_field", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.PlifeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Cy")
                        .HasColumnType("int")
                        .HasColumnName("cy");

                    b.Property<int>("F")
                        .HasColumnType("int")
                        .HasColumnName("f");

                    b.Property<int>("Fh")
                        .HasColumnType("int")
                        .HasColumnName("fh");

                    b.Property<int>("Hide")
                        .HasColumnType("int")
                        .HasColumnName("hide");

                    b.Property<int>("Life")
                        .HasColumnType("int")
                        .HasColumnName("life");

                    b.Property<int>("Map")
                        .HasColumnType("int")
                        .HasColumnName("map");

                    b.Property<int>("Mobtime")
                        .HasColumnType("int")
                        .HasColumnName("mobtime");

                    b.Property<int>("Rx0")
                        .HasColumnType("int")
                        .HasColumnName("rx0");

                    b.Property<int>("Rx1")
                        .HasColumnType("int")
                        .HasColumnName("rx1");

                    b.Property<int>("Team")
                        .HasColumnType("int")
                        .HasColumnName("team");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'n'");

                    b.Property<int>("World")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("world")
                        .HasDefaultValueSql("'-1'");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("plife", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.ReactorDropEntity", b =>
                {
                    b.Property<int>("Reactordropid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("reactordropid");

                    b.Property<int>("Chance")
                        .HasColumnType("int")
                        .HasColumnName("chance");

                    b.Property<int>("Itemid")
                        .HasColumnType("int")
                        .HasColumnName("itemid");

                    b.Property<int>("Questid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("questid")
                        .HasDefaultValueSql("'-1'");

                    b.Property<int>("Reactorid")
                        .HasColumnType("int")
                        .HasColumnName("reactorid");

                    b.HasKey("Reactordropid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Reactorid" }, "reactorid");

                    b.ToTable("sys_reactordrops", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Chatlog")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chatlog");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<sbyte>("Reason")
                        .HasColumnType("tinyint")
                        .HasColumnName("reason");

                    b.Property<int>("Reporterid")
                        .HasColumnType("int")
                        .HasColumnName("reporterid");

                    b.Property<DateTime>("Reporttime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("reporttime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Victimid")
                        .HasColumnType("int")
                        .HasColumnName("victimid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.RingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CharacterId1")
                        .HasColumnType("int")
                        .HasColumnName("characterId1");

                    b.Property<int>("CharacterId2")
                        .HasColumnType("int")
                        .HasColumnName("characterId2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("itemid");

                    b.Property<long>("RingId1")
                        .HasColumnType("bigint")
                        .HasColumnName("ringId1");

                    b.Property<long>("RingId2")
                        .HasColumnType("bigint")
                        .HasColumnName("ringId2");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("rings", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.ShopEntity", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("shopid");

                    b.Property<int>("NpcId")
                        .HasColumnType("int")
                        .HasColumnName("npcid");

                    b.HasKey("ShopId")
                        .HasName("PRIMARY");

                    b.ToTable("sys_shops", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.Shopitem", b =>
                {
                    b.Property<int>("Shopitemid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("shopitemid");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("itemid");

                    b.Property<int>("Pitch")
                        .HasColumnType("int")
                        .HasColumnName("pitch");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position")
                        .HasComment("sort is an arbitrary field designed to give leeway when modifying shops. The lowest number is 104 and it increments by 4 for each item to allow decent space for swapping/inserting/removing items.");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int>("Shopid")
                        .HasColumnType("int")
                        .HasColumnName("shopid");

                    b.HasKey("Shopitemid")
                        .HasName("PRIMARY");

                    b.ToTable("sys_shopitems", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.SpecialCashItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Info")
                        .HasColumnType("int")
                        .HasColumnName("info");

                    b.Property<int>("Modifier")
                        .HasColumnType("int")
                        .HasColumnName("modifier")
                        .HasComment("1024 is add/remove");

                    b.Property<int>("Sn")
                        .HasColumnType("int")
                        .HasColumnName("sn");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("sys_specialcashitems", (string)null);
                });

            modelBuilder.Entity("Application.EF.NewYearCardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("message")
                        .HasDefaultValueSql("''");

                    b.Property<bool>("Received")
                        .HasColumnType("INTEGER")
                        .HasColumnName("received");

                    b.Property<bool>("ReceiverDiscard")
                        .HasColumnType("INTEGER")
                        .HasColumnName("receiverdiscard");

                    b.Property<int>("ReceiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("receiverid")
                        .HasDefaultValueSql("'-1'");

                    b.Property<bool>("SenderDiscard")
                        .HasColumnType("INTEGER")
                        .HasColumnName("senderdiscard");

                    b.Property<int>("SenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("senderid")
                        .HasDefaultValueSql("'-1'");

                    b.Property<long>("TimeReceived")
                        .HasColumnType("bigint")
                        .HasColumnName("timereceived");

                    b.Property<long>("TimeSent")
                        .HasColumnType("bigint")
                        .HasColumnName("timesent");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("newyear", (string)null);
                });

            modelBuilder.Entity("Application.EF.NoteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted");

                    b.Property<int>("Fame")
                        .HasColumnType("int")
                        .HasColumnName("fame");

                    b.Property<int>("FromId")
                        .HasColumnType("int")
                        .HasColumnName("fromId");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.Property<int>("ToId")
                        .HasColumnType("int")
                        .HasColumnName("toId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Application.EF.Entities.FamilyCharacterEntity", b =>
                {
                    b.HasOne("Application.EF.Entities.CharacterEntity", "CidNavigation")
                        .WithOne("FamilyCharacter")
                        .HasForeignKey("Application.EF.Entities.FamilyCharacterEntity", "Cid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("family_character_ibfk_1");

                    b.Navigation("CidNavigation");
                });

            modelBuilder.Entity("Application.EF.Entities.CharacterEntity", b =>
                {
                    b.Navigation("FamilyCharacter");
                });
#pragma warning restore 612, 618
        }
    }
}
