using Application.EF.Entities;
using Application.Shared.Constants;
using Google.Protobuf;

namespace Application.Core.EF.SeedData;

public static class AdminSeedData
{
    public static readonly AccountEntity Account = new(
        "admin",
        "C7AD44CBAD762A5DA0A452F9E854FDC1E0E7A52A38015F23F3EAB1D80B931DD472634DFAC71CD34EBC35D16AB7FB8A90C81F975113D6C7538DC69DD8DE9077EC"
    )
    {
        Id = 1,
        Pin = "0000",
        Pic = "000000",
        Createdat = new DateTimeOffset(2021, 5, 24, 8, 0, 2, TimeSpan.Zero),
        Birthday = new DateTime(2005, 5, 11),
        NxCredit = 1000000,
        MaplePoint = 1000000,
        NxPrepaid = 1000000,
        Characterslots = 3,
        Gender = 0,
        Tos = true,
        GMLevel = 6,
        Nick = null,
        Email = null
    };

    public static CharacterEntity GenerateAdminCharacter()
    {
        var admin = new CharacterEntity(
            accountId: 1,
            name: "Admin",
            level: 1,
            exp: 0,
            gachaexp: 0,
            str: 12,
            dex: 5,
            luk: 4,
            @int: 4,
            hp: 50,
            mp: 5,
            maxhp: 50,
            maxmp: 5,
            meso: 0,
            job: 0,
            skincolor: 0,
            gender: 0,
            hair: 30030,
            face: 20000,
            map: 10000,
            spawnpoint: 2,
            ap: 0,
            sp: "0,0,0,0,0,0,0,0,0,0"
        )
        {
            Id = 1,
            HpMpUsed = 0,
            Fame = 0,
            Fquest = 0,
            BuddyCapacity = 25,
            CreateDate = new DateTimeOffset(2021, 5, 24, 8, 0, 3, TimeSpan.Zero),
            Rank = 1,
            RankMove = 0,
            JobRank = 1,
            JobRankMove = 0,
            GuildId = 0,
            GuildRank = 5,
            MountLevel = 1,
            MountExp = 0,
            Mounttiredness = 0,
            Omokwins = 0,
            Omoklosses = 0,
            Omokties = 0,
            Matchcardwins = 0,
            Matchcardlosses = 0,
            Matchcardties = 0,
            Equipslots = DefaultConfigs.BagSize,
            Useslots = DefaultConfigs.BagSize,
            Setupslots = DefaultConfigs.BagSize,
            Etcslots = DefaultConfigs.BagSize,
            FamilyId = -1,
            Monsterbookcover = 0,
            AllianceRank = 5,
            VanquisherStage = 0,
            AriantPoints = 0,
            DojoPoints = 0,
            LastDojoStage = 0,
            FinishedDojoTutorial = false,
            VanquisherKills = 0,
            SummonValue = 0,
            Pqpoints = 0,
            DataString = "",
            LastLogoutTime = new DateTimeOffset(2021, 5, 24, 8, 0, 4, TimeSpan.Zero),
            LastExpGainTime = new DateTimeOffset(2015, 1, 1, 13, 0, 0, TimeSpan.Zero),
            PartySearch = true,
            Jailexpire = 0,
        };
        var data = new ProtoModel.CharacterDataProto() { GachaponStorage = new(), Bag = new ProtoModel.CharacterBagDataProto() };
        data.Bag.EtcInv.Add(
            new ProtoModel.ItemProto()
            {
                UniqueId = -1,
                Itemid = 4161001,
                Position = 1,
                Quantity = 1,
                Owner = "",
                Flag = 0,
                Expiration = -1,
                GiftFrom = "",
                Properties = null,
            }
        );

        data.Bag.EquippedInv.Add(new ProtoModel.ItemProto()
        {
            UniqueId = -1,
            Itemid = 1040002,
            Position = -5,
            Quantity = 1,
            Owner = "",
            Flag = 0,
            Expiration = -1,
            GiftFrom = "",
            Properties = null,
            EquipInfo = new ProtoModel.EquipProto
            {
                Upgradeslots = 7,
                Level = 0,
                Str = 0,
                Dex = 0,
                Int = 0,
                Luk = 0,
                Hp = 0,
                Mp = 0,
                Watk = 0,
                Matk = 0,
                Wdef = 3,
                Mdef = 0,
                Acc = 0,
                Avoid = 0,
                Hands = 0,
                Speed = 0,
                Jump = 0,
                Locked = 0,
                Vicious = 0,
                Itemlevel = 1,
                Itemexp = 0,
            },
        });
        data.Bag.EquippedInv.Add(new ProtoModel.ItemProto()
        {
            UniqueId = -1,
            Itemid = 1060002,
            Position = -6,
            Quantity = 1,
            Owner = "",
            Flag = 0,
            Expiration = -1,
            GiftFrom = "",
            Properties = null,
            EquipInfo = new ProtoModel.EquipProto()
            {
                Upgradeslots = 7,
                Level = 0,
                Str = 0,
                Dex = 0,
                Int = 0,
                Luk = 0,
                Hp = 0,
                Mp = 0,
                Watk = 0,
                Matk = 0,
                Wdef = 2,
                Mdef = 0,
                Acc = 0,
                Avoid = 0,
                Hands = 0,
                Speed = 0,
                Jump = 0,
                Locked = 0,
                Vicious = 0,
                Itemlevel = 1,
                Itemexp = 0,
            },
        });
        data.Bag.EquippedInv.Add(new ProtoModel.ItemProto()
        {
            UniqueId = -1,
            Itemid = 1072001,
            Position = -7,
            Quantity = 1,
            Owner = "",
            Flag = 0,
            Expiration = -1,
            GiftFrom = "",
            Properties = null,
            EquipInfo = new ProtoModel.EquipProto
            {
                Upgradeslots = 5,
                Level = 0,
                Str = 0,
                Dex = 0,
                Int = 0,
                Luk = 0,
                Hp = 0,
                Mp = 0,
                Watk = 0,
                Matk = 0,
                Wdef = 2,
                Mdef = 0,
                Acc = 0,
                Avoid = 0,
                Hands = 0,
                Speed = 0,
                Jump = 0,
                Locked = 0,
                Vicious = 0,
                Itemlevel = 1,
                Itemexp = 0,
            },
        });
        data.Bag.EquippedInv.Add(new ProtoModel.ItemProto()
        {
            UniqueId = -1,
            Itemid = 1302000,
            Position = -11,
            Quantity = 1,
            Owner = "",
            Flag = 0,
            Expiration = -1,
            GiftFrom = "",
            Properties = null,
            EquipInfo = new ProtoModel.EquipProto
            {
                Upgradeslots = 7,
                Level = 0,
                Str = 0,
                Dex = 0,
                Int = 0,
                Luk = 0,
                Hp = 0,
                Mp = 0,
                Watk = 17,
                Matk = 0,
                Wdef = 0,
                Mdef = 0,
                Acc = 0,
                Avoid = 0,
                Hands = 0,
                Speed = 0,
                Jump = 0,
                Locked = 0,
                Vicious = 0,
                Itemlevel = 1,
                Itemexp = 0,
            },
        });

        admin.Blob = data.ToByteArray();
        return admin;
    }

    //public static readonly List<KeyMapEntity> KeyMaps =
    //[
    //    new(1, 18, 4, 0) { Id = 161 },
    //    new(1, 65, 6, 106) { Id = 162 },
    //    new(1, 2, 4, 10) { Id = 163 },
    //    new(1, 23, 4, 1) { Id = 164 },
    //    new(1, 3, 4, 12) { Id = 165 },
    //    new(1, 4, 4, 13) { Id = 166 },
    //    new(1, 5, 4, 18) { Id = 167 },
    //    new(1, 6, 4, 24) { Id = 168 },
    //    new(1, 16, 4, 8) { Id = 169 },
    //    new(1, 17, 4, 5) { Id = 170 },
    //    new(1, 19, 4, 4) { Id = 171 },
    //    new(1, 25, 4, 19) { Id = 172 },
    //    new(1, 26, 4, 14) { Id = 173 },
    //    new(1, 27, 4, 15) { Id = 174 },
    //    new(1, 31, 4, 2) { Id = 175 },
    //    new(1, 34, 4, 17) { Id = 176 },
    //    new(1, 35, 4, 11) { Id = 177 },
    //    new(1, 37, 4, 3) { Id = 178 },
    //    new(1, 38, 4, 20) { Id = 179 },
    //    new(1, 40, 4, 16) { Id = 180 },
    //    new(1, 43, 4, 9) { Id = 181 },
    //    new(1, 44, 5, 50) { Id = 182 },
    //    new(1, 45, 5, 51) { Id = 183 },
    //    new(1, 46, 4, 6) { Id = 184 },
    //    new(1, 50, 4, 7) { Id = 185 },
    //    new(1, 56, 5, 53) { Id = 186 },
    //    new(1, 59, 6, 100) { Id = 187 },
    //    new(1, 60, 6, 101) { Id = 188 },
    //    new(1, 61, 6, 102) { Id = 189 },
    //    new(1, 62, 6, 103) { Id = 190 },
    //    new(1, 63, 6, 104) { Id = 191 },
    //    new(1, 64, 6, 105) { Id = 192 },
    //    new(1, 57, 5, 54) { Id = 193 },
    //    new(1, 48, 4, 22) { Id = 194 },
    //    new(1, 29, 5, 52) { Id = 195 },
    //    new(1, 7, 4, 21) { Id = 196 },
    //    new(1, 24, 4, 25) { Id = 197 },
    //    new(1, 33, 4, 26) { Id = 198 },
    //    new(1, 41, 4, 23) { Id = 199 },
    //    new(1, 39, 4, 27) { Id = 200 },
    //];
}
