syntax = "proto3";

import "Dto/Item.proto";
import "Dto/Monsterbook.proto";
import "Dto/PetIgnore.proto";
import "Dto/TrockLocation.proto";
import "Dto/Area.proto";
import "Dto/Event.proto";
import "Dto/QuestStatus.proto";
import "Dto/Skill.proto";
import "Dto/SkillMacro.proto";
import "Dto/CoolDown.proto";
import "Dto/KeyMap.proto";
import "Dto/SavedLocation.proto";
import "Dto/QuickSlot.proto";
import "Dto/Storage.proto";
import "Dto/Fame.proto";
import "Sync/PlayerTimerQuest.proto";
import "Buddy/Buddy.proto";
import "Dto/NewYearCard.proto";

package Dto;

message CharacterDataProto {
  CharacterBagDataProto bag = 1; // 背包
  repeated Dto.MonsterbookDto monsterBooks = 3; // 怪物卡片
  repeated Dto.PetIgnoreDto petIgnores = 4; // 宠物忽略设置
  repeated Dto.TrockLocationDto trockLocations = 5; // 缩地石记录
  repeated Dto.AreaDto areas = 6; // 已访问区域记录
  repeated Dto.EventDto events = 7; // ？
  repeated Dto.QuestStatusDto questStatuses = 8; // 任务记录
  repeated Dto.SkillDto skills = 9; // 技能
  repeated Dto.SkillMacroDto skillMacros = 10; // 技能宏
  repeated Dto.CoolDownDto coolDowns = 11; // 冷却
  repeated Dto.KeyMapDto keyMaps = 12; // 快捷键
  repeated Dto.SavedLocationDto savedLocations = 13; // 最近地图保存点
  repeated int32 wishItems = 14;	// 愿望单
  repeated Dto.FameLogRecordDto fameLogs = 15;	// 被加人气记录
  repeated SyncProto.PlayerTimerQuestDto runningTimerQuests = 16;	// 计时任务
  Dto.StorageDto gachaponStorage = 17;	// 奖品仓库
  repeated BuddyProto.BuddyDto buddyList = 18; // 好友
}

message CharacterBagDataProto {
	repeated Dto.ItemDto equipInv = 1;
	repeated Dto.ItemDto useInv = 2;
	repeated Dto.ItemDto setupInv = 3;
	repeated Dto.ItemDto etcInv = 4;
	repeated Dto.ItemDto cashInv = 5;
	repeated Dto.ItemDto equippedInv = 6;
}