# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Check

on:
  pull_request:
    branches:
      - "master"
    paths:
      - 'src/**/*.csproj'
      - 'src/**/*.cs' 
      - 'test/**/*.csproj'
      - 'test/**/*.cs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  BuildAndTest:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    env:
      RUA_MS_WZConfig__BaseDir: ${{ github.workspace }}/src/Application.Resources/wz
      RUA_MS_ScriptConfig__BaseDir: ${{ github.workspace }}/src/Application.Resources/scripts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore "./src/Application.Host/Application.Host.csproj"

      - name: Build Host
        run: dotnet build "./src/Application.Host/Application.Host.csproj" --no-restore -c Release

      - name: Test Infrastructure
        run: dotnet test  --filter "FullyQualifiedName~ServiceTest.Infrastructure" --blame-crash --logger "GitHubActions;verbosity=detailed" "./test/ServiceTest/ServiceTest.csproj"

      - name: Test Server
        run: dotnet test  --filter "FullyQualifiedName~ServiceTest.Games" --blame-crash --logger "GitHubActions;verbosity=detailed" "./test/ServiceTest/ServiceTest.csproj"

  review:
    runs-on: ubuntu-latest
    needs: BuildAndTest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: https://api.deepseek.com
          MODEL: deepseek-v4-flash

          # common
          LANGUAGE: Chinese
          PROMPT: "请检查差异代码中的逻辑错误、潜在bug和代码风格问题："
          top_p: 1
          temperature: 1
          max_tokens: 10000
          MAX_PATCH_LENGTH: 10000 # 单个 diff 超过此长度将跳过评审
          INCLUDE_PATTERNS: "*.cs"
          IGNORE_PATTERNS: "**/Migrations/**/*.cs"
